### ISSUE TITLE
AttributeError: 'EasyDict' object has no attribute 'OHEM_MODE'

### ISSUE THREAD

**Issue by jingruhou** [deepinsight/insightface#1016]
INFO:root:output shape {'blockgrad0_output': (8, 800),
 'blockgrad1_output': (8, 8, 400),
 'blockgrad2_output': (8, 20, 400),
 'blockgrad3_output': (8, 3200),
 'blockgrad4_output': (8, 8, 1600),
 'blockgrad5_output': (8, 20, 1600),
 'blockgrad6_output': (8, 12800),
 'blockgrad7_output': (8, 8, 6400),
 'blockgrad8_output': (8, 20, 6400),
 'face_rpn_bbox_loss_stride16_output': (8, 8, 1600),
 'face_rpn_bbox_loss_stride32_output': (8, 8, 400),
 'face_rpn_bbox_loss_stride8_output': (8, 8, 6400),
 'face_rpn_cls_prob_stride16_output': (8, 2, 3200),
 'face_rpn_cls_prob_stride32_output': (8, 2, 800),
 'face_rpn_cls_prob_stride8_output': (8, 2, 12800),
 'face_rpn_landmark_loss_stride16_output': (8, 20, 1600),
 'face_rpn_landmark_loss_stride32_output': (8, 20, 400),
 'face_rpn_landmark_loss_stride8_output': (8, 20, 6400)}
fixed []
INFO:root:lr 0.001000 lr_epoch_diff [1, 2, 3, 4, 5, 55, 68, 80] lr_steps [(3219, 1.5849), (6438, 1.5849), (9657, 1.5849), (12876, 1.5849), (16095, 1.5849), (177045, 0.1), (218892, 0.1), (257520, 0.1)]
Error in rpn_fpn_ohem3.create_operator: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mxnet/operator.py", line 968, in create_operator_entry
    op = op_prop.create_operator(ctx, shapes, dtypes)
  File "/home1/houjr/project/insightface/RetinaFace/rcnn/PY_OP/rpn_fpn_ohem3.py", line 162, in create_operator
    return RPNFPNOHEM3Operator(self.stride, self.network, self.dataset, self.prefix)
  File "/home1/houjr/project/insightface/RetinaFace/rcnn/PY_OP/rpn_fpn_ohem3.py", line 19, in __init__
    self.mode = config.TRAIN.OHEM_MODE #0 for random 10:245, 1 for 10:246, 2 for 10:30, mode 1 for default
AttributeError: 'EasyDict' object has no attribute 'OHEM_MODE'

Traceback (most recent call last):
  File "train.py", line 375, in <module>
    main()
  File "train.py", line 372, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train.py", line 321, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 498, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 1629, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
face_bbox_weight_stride8: (8, 8, 6400)
face_landmark_weight_stride32: (8, 20, 400)
face_label_stride8: (8, 12800)
face_landmark_target_stride8: (8, 20, 6400)
face_landmark_target_stride16: (8, 20, 1600)
face_landmark_weight_stride16: (8, 20, 1600)
face_landmark_target_stride32: (8, 20, 400)
face_label_stride32: (8, 800)
face_label_stride16: (8, 3200)
face_bbox_target_stride32: (8, 8, 400)
face_bbox_weight_stride16: (8, 8, 1600)
face_bbox_target_stride16: (8, 8, 1600)
face_bbox_weight_stride32: (8, 8, 400)
face_landmark_weight_stride8: (8, 20, 6400)
data: (8, 3, 640, 640)
face_bbox_target_stride8: (8, 8, 6400)
[11:00:51] src/operator/custom/custom.cc:282: Check failed: reinterpret_cast<CustomOpCreateFunc>( params.info->callbacks[kCustomOpPropCreateOperator])( os.str().c_str(), shapes.size(), shapes.data(), ndims.data(), in_type.data(), op_info, params.info->contexts[kCustomOpPropCreateOperator]): 
Stack trace:
  [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x4958fb) [0x7fac7d5e18fb]
  [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x7d09d9) [0x7fac7d91c9d9]
  [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x7c4715) [0x7fac7d910715]
  [bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x25bd50d) [0x7fac7f70950d]
  [bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x25c0b68) [0x7fac7f70cb68]
  [bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::FinishInitGraph(nnvm::Symbol, nnvm::Graph, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x793) [0x7fac7f739bc3]
  [bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, mxnet::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x73d) [0x7fac7f74037d]
  [bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, mxnet::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*)+0x8a8) [0x7fac7f741228]
  [bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorSimpleBindEx+0x221b) [0x7fac7f682d9b]

**Comment by jingruhou** [comment]
Does anyone encounter this problem?

**Comment by jingruhou** [comment]
File "/home1/houjr/project/insightface/RetinaFace/rcnn/PY_OP/rpn_fpn_ohem3.py", line 19, in init
self.mode = config.TRAIN.OHEM_MODE #0 for random 10:245, 1 for 10:246, 2 for 10:30, mode 1 for default

modify **self.mode = 1**
