### ISSUE TITLE
testing pre trained model getting issue.

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [deepinsight/insightface#1022]
@yingfeng 
python test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import face_model
  File "/media/administrator/hdd/Age_gender_identification/insightface/gender-age/face_model.py", line 11, in <module>
    import mxnet as mx
  File "/home/administrator/gender_identification/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/administrator/gender_identification/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/administrator/gender_identification/lib/python3.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/administrator/gender_identification/lib/python3.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory**

**Comment by Bryan-bai** [comment]
check the libcudart.so. It may be not installed.

**Comment by NarasimmanSaravana1994** [comment]
The issue resolved
