### ISSUE TITLE
Start to train the model of RetinaFace, 

### ISSUE THREAD

**Issue by angular-elrond** [deepinsight/insightface#1026]
Hello, I am a new user, install all dependencies, while compiling the train.py file it gives bellow error and in my computer, there is not support of GPU
Traceback (most recent call last):
  File "insightface/RetinaFace/train.py", line 14, in <module>
    from rcnn.symbol import *
  File "insightface\RetinaFace\rcnn\symbol\__init__.py", line 2, in <module>
    from .symbol_mnet import *
  File "insightface\RetinaFace\rcnn\symbol\symbol_mnet.py", line 9, in <module>
    from rcnn.symbol.symbol_common import get_sym_train
  File "insightface\RetinaFace\rcnn\symbol\symbol_common.py", line 5, in <module>
    from rcnn.PY_OP import rpn_fpn_ohem3, cascade_refine
  File "insightface\RetinaFace\rcnn\PY_OP\cascade_refine.py", line 9, in <module>
    from ..processing.generate_anchor import generate_anchors, anchors_plane
  File "insightface\RetinaFace\rcnn\processing\generate_anchor.py", line 8, in <module>
    from ..cython.anchors import anchors_cython
ModuleNotFoundError: No module named 'rcnn.cython.anchors'

**Comment by nttstar** [comment]
type ``make`` first to install cxx modules
