### ISSUE TITLE
Using the model arcface_r100_v1 and command get_embedding raises AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by woreom** [deepinsight/insightface#1052]
So I'm using the pre-trained model arcface_r100_v1 and img='https://drive.google.com/open?id=16PKySktkjj3579S1F9a9mmCmMRm1fH8u', I get the error AttributeError: 'NoneType' object has no attribute 'shape'

I am using the python 2.7 insightface package.

Here is the log:

Traceback (most recent call last):
  File "FaceRecognitionTest.py", line 55, in <module>
    emb2 = model.get_embedding(img2)
  File "/usr/local/lib/python2.7/dist-packages/insightface/model_zoo/face_recognition.py", line 48, in get_embedding
    assert img.shape[2]==3 and img.shape[0:2]==self.image_size
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by rkinas** [comment]
I have the same problem :(

**Comment by woreom** [comment]
> I have the same problem :(

I think I worked around this by resizing pictures to 112x112

**Comment by GianniGi** [comment]
works by resetting runtime of colab

**Comment by Sejani-Parth** [comment]
> works by resetting runtime of colab

me to
