### ISSUE TITLE
I use the a P100 GPU,but get the error,can you give me some advice? Thank you!

### ISSUE THREAD

**Issue by SongyiGao** [deepinsight/insightface#107]
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [400000, 560000, 640000]
[15:20:42] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[15:20:43] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [15:20:43] src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7fe6be4d37cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1242238) [0x7fe6bf540238]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1244c0a) [0x7fe6bf542c0a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4d4db) [0x7fe6bf14b4db]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe549cd) [0x7fe6bf1529cd]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe59f95) [0x7fe6bf157f95]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe5d6ee) [0x7fe6bf15b6ee]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe5dcd4) [0x7fe6bf15bcd4]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorSimpleBind+0x2261) [0x7fe6bf0da291]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fe6e3522e40]

Traceback (most recent call last):
  File "train_softmax.py", line 453, in <module>
    main()
  File "train_softmax.py", line 450, in main
    train_net(args)
  File "train_softmax.py", line 444, in train_net
    epoch_end_callback = epoch_cb )
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 460, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 417, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 231, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 327, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 603, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol.py", line 1479, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 3, 112, 112)
softmax_label: (128,)
[15:20:43] src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7fe6be4d37cc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1242238) [0x7fe6bf540238]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x1244c0a) [0x7fe6bf542c0a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe4d4db) [0x7fe6bf14b4db]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe549cd) [0x7fe6bf1529cd]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe59f95) [0x7fe6bf157f95]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe5d6ee) [0x7fe6bf15b6ee]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xe5dcd4) [0x7fe6bf15bcd4]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorSimpleBind+0x2261) [0x7fe6bf0da291]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fe6e3522e40]

**Comment by aitaoquanyi** [comment]
adjust batch size or use other small models( res18/res34....). GPU out of memory.

**Comment by xxllp** [comment]
训练太慢了吧
