### ISSUE TITLE
  When using Python 3, I found a very strange problem. Please let me know. Thank you very much

### ISSUE THREAD

**Issue by xianglei3** [deepinsight/insightface#1103]
call reset()
Traceback (most recent call last):
  File "train.py", line 1025, in <module>
    main()
  File "train.py", line 1022, in main
    train_net(args)
  File "train.py", line 1016, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/xl/anaconda3/envs/test/lib/python3.5/site-packages/mxnet/module/base_module.py", line 520, in fit
    next_data_batch = next(data_iter)
  File "/home/xl/anaconda3/envs/test/lib/python3.5/site-packages/mxnet/io/io.py", line 230, in __next__
    return self.next()
  File "/home/xl/1mxnetinsight/insightface-master/src/data.py", line 860, in next
    self.reset()
  File "/home/xl/1mxnetinsight/insightface-master/src/data.py", line 753, in reset
    random.shuffle(self.seq)
  File "/home/xl/anaconda3/envs/test/lib/python3.5/random.py", line 281, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'range' object does not support item assignment
(test) xl@xl-Alienware-13-R3:~/1mxnetinsight/insightface-master/src$

**Comment by tbuikr** [comment]
In python3, the range does not return a list, so you should convert `self.seq` to list in line 753 of data.py
```
random.shuffle(list(self.seq))
```
