### ISSUE TITLE
  When I use my own bin file for training, the following error occurs. I sincerely look forward to your reply, no matter how I repay you

### ISSUE THREAD

**Issue by xianglei3** [deepinsight/insightface#1122]
/home/xl/anaconda3/envs/test/lib/python3.5/site-packages/mxnet/module/base_module.py:504: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.3333333333333333). Is this intended?
  optimizer_params=optimizer_params)
call reset()
Traceback (most recent call last):
  File "/home/xl/1mxnetinsight/insightface-master/src/data.py", line 873, in next
    label, s, bbox, landmark = self.next_sample()
  File "/home/xl/1mxnetinsight/insightface-master/src/data.py", line 766, in next_sample
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 1025, in <module>
    main()
  File "train.py", line 1022, in main
    train_net(args)
  File "train.py", line 1016, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/xl/anaconda3/envs/test/lib/python3.5/site-packages/mxnet/module/base_module.py", line 520, in fit
    next_data_batch = next(data_iter)
  File "/home/xl/anaconda3/envs/test/lib/python3.5/site-packages/mxnet/io/io.py", line 230, in __next__
    return self.next()
  File "/home/xl/1mxnetinsight/insightface-master/src/data.py", line 945, in next
    raise StopIteration
StopIteration

the commond is  : CUDA_VISIBLE_DEVICES='0' python -u train.py --network r100  --data-dir   /home/xl/1mxnetinsight/insightface-master/datasets/17_faces_datasets  --ckpt 2 --target 17_faces --version-se 0 --per-batch-size 3 --prefix  /media/xl/绿叶启动盘/save/model  --verbose 10 --lr 0.00001

**Comment by umairanis03** [comment]
Hi @xianglei3 
How are you preparing our .bin files?

I have correct way of preparing our own train.rec for training and .bin files for verification, please let me know if I can help you.

**Comment by Math2code** [comment]
@umairanis03 Could you tell me what's the correct way to prepare the .bin files?

**Comment by umairanis03** [comment]
@Math2code Please look my repository regarding the same: https://github.com/umairanis03/facial-recognition/blob/master/validation_prep.md

I hope it will help!

**Comment by YTEP-ZHI** [comment]
@umairanis03  Wow it really helps, thanks for your sharing.

**Comment by eeric** [comment]
> train.rec

please tell me how to make train.rec?
