### ISSUE TITLE
coverted mnet-cov2 to onnx  error

### ISSUE THREAD

**Issue by xingha** [deepinsight/insightface#1145]
python convert_onnx.py --prefix /run/media/insightface/RetinaFaceAntiCov/model/mnet_cov2 --output-onnx mnet_cov2.onnx
mxnet version: 1.5.1
onnx version: 1.2.1
input-shape: (1, 3, 112, 112)
[11:37:12] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[11:37:12] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "convert_onnx.py", line 30, in <module>
    converted_model_path = onnx_mxnet.export_model(sym_file, params_file, [input_shape], np.float32, args.output_onnx)
  File "/run/media/virtualenv/maxnet_py3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 83, in export_model
    verbose=verbose)
  File "/run/media//virtualenv/maxnet_py3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 253, in create_onnx_graph_proto
    idx=idx
  File "/run/media/virtualenv/maxnet_py3/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 90, in convert_layer
    raise AttributeError("No conversion function registered for op type %s yet." % op)
AttributeError: No conversion function registered for op type SoftmaxActivation yet.

**Comment by jm-pro** [comment]
see workarounds https://github.com/deepinsight/insightface/issues/858
and https://github.com/onnx/onnx/issues/2000

**Comment by xingha** [comment]
th

**Comment by zheshipinyinMc** [comment]
https://github.com/zheshipinyinMc/arcface_retinaface_mxnet2onnx
https://zhuanlan.zhihu.com/p/166267806
