### ISSUE TITLE
out of memory when run with four Titanxp even per-batch-size is 1

### ISSUE THREAD

**Issue by MoeLau** [deepinsight/insightface#115]
how should I solve it?
gpu num: 4
num_layers 50
image_size [112, 112]
num_classes 85164
Called with argument: Namespace(batch_size=4, beta=1000.0, beta_freeze=0, beta_min=5.0, ckpt=1, ctx_num=4, cutoff=0, data_dir='datasets/faces_ms1m_112x112', easy_margin=0, emb_size=512, end_epoch=100000, gamma=0.12, image_channel=3, image_h=112, image_w=112, loss_type=4, lr=0.1, lr_steps='', margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.5, margin_s=64.0, max_steps=0, mom=0.9, network='r50', num_classes=85164, num_layers=50, per_batch_size=1, power=1.0, prefix='models/model-r50', pretrained='', rand_mirror=1, rescale_threshold=0, scale=0.9993, target='lfw', use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
init resnet 50
0 1 E 3 prelu
INFO:root:loading recordio datasets/faces_ms1m_112x112/train.rec...
header0 label [ 3804847.  3890011.]
id2range 85164
3804846
rand_mirror 1
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver lfw
lr_steps [12800000, 17920000, 20480000]
[10:02:31] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
call reset()
Traceback (most recent call last):
  File "/home/liumeng/insightface-master/src/train_softmax.py", line 464, in <module>
    main()
  File "/home/liumeng/insightface-master/src/train_softmax.py", line 461, in main
    train_net(args)
  File "/home/liumeng/insightface-master/src/train_softmax.py", line 455, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/liumeng/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/base_module.py", line 488, in fit
    self.update()
  File "/home/liumeng/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/module/module.py", line 643, in update
    self._kvstore, self._exec_group.param_names)
  File "/home/liumeng/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/model.py", line 134, in _update_params_on_kvstore
    kvstore.push(name, grad_list, priority=-index)
  File "/home/liumeng/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/kvstore.py", line 224, in push
    self.handle, mx_uint(len(ckeys)), ckeys, cvals, ctypes.c_int(priority)))
  File "/home/liumeng/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:03:34] src/storage/./pooled_storage_manager.h:107: cudaMalloc failed: out of memory

**Comment by MoeLau** [comment]
From observation，only 1177M is used for each GPU.

**Comment by Jumabek** [comment]
I have similar question, what is the minimum gpu memory requirement for training with batch_size 1?

**Comment by Lane565** [comment]
Same problem here. But it solved when I used 6*1080Ti.

**Comment by nttstar** [comment]
maybe a bug of MXNet
