### ISSUE TITLE
error in own dataset  when i train

### ISSUE THREAD

**Issue by herokarimpoor** [deepinsight/insightface#1166]
hello
i genarate .lst and .rec and .idx
but when i tarin 
Give me this error
Network FLOPs: 24.2G
INFO:root:loading recordio ../datasets/train.rec...
Traceback (most recent call last):
  File "train.py", line 378, in <module>
    main()
  File "train.py", line 375, in main
    train_net(args)
  File "train.py", line 243, in train_net
    images_filter        = config.data_images_filter,
  File "/home/ml/insightface-master/recognition/image_iter.py", line 39, in __init__
    s = self.imgrec.read_idx(0)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/recordio.py", line 313, in read_idx
    self.seek(idx)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/recordio.py", line 275, in seek
    pos = ctypes.c_size_t(self.idx[idx])
KeyError: 0
[14:51:49] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice

please help me

**Comment by xiaose26** [comment]
same error

**Comment by xiaose26** [comment]
maybe your image index start from 1 not 0,you should check your *.lst file at col[0]
