### ISSUE TITLE
ImportError: No module named bbox

### ISSUE THREAD

**Issue by normarclone** [deepinsight/insightface#1175]
I did test.py in RetinaFace then I got this problem
>python test.py

>   File "test.py", line 7, in <module>
    from retinaface import RetinaFace
  File "C:\Users\Admin\Desktop\AI\AI Face\insightface-master\RetinaFace\retinaface.py", line 13, in <module>
    from rcnn.processing.bbox_transform import clip_boxes
  File "C:\Users\Admin\Desktop\AI\AI Face\insightface-master\RetinaFace\rcnn\processing\bbox_transform.py", line 2, in <module>
    from ..cython.bbox import bbox_overlaps_cython
ModuleNotFoundError: No module named 'rcnn.cython.bbox'

I found that I have to "make" first! So I ran this command in cython folder

>python setup.py build_ext --inplace 

But I got this Error

>Traceback (most recent call last):
  File "setup.py", line 168, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 115, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 88, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

How can I solve this problem? Please help me!

**Comment by bartolootrit** [comment]
You may take a look at this question: [AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'](https://stackoverflow.com/questions/52550831/attributeerror-msvccompiler-object-has-no-attribute-compiler-so)

**Comment by randallsalvares** [comment]
If you want to fix this yourself, I recommend looking for any line of your setup.py file containing the "self.compiler.compiler[0]" part and commenting it out.
