### ISSUE TITLE
how to finetune pretrained-model R50 of retinaface

### ISSUE THREAD

**Issue by spy78111** [deepinsight/insightface#1177]
when I trained retinaface using pretrained model R50, it occurs errors:
INFO:root:loading model/retina,0
(0, 'data', 648, (1, 3, 640, 640))
(1, 'bn_data_gamma', 648, (3,))
(2, 'bn_data_beta', 648, (3,))
(3, 'bn_data_moving_mean', 648, (3,))
(4, 'bn_data_moving_var', 648, (3,))
(5, 'bn_data_output', 648, (1, 3, 640, 640))
(6, 'conv0_weight', 648, (64, 3, 7, 7))
(7, 'conv0_output', 648, (1, 64, 320, 320))
(8, 'bn0_gamma', 648, (64,))
(9, 'bn0_beta', 648, (64,))
(10, 'bn0_moving_mean', 648, (64,))
(11, 'bn0_moving_var', 648, (64,))
(12, 'bn0_output', 648, (1, 64, 320, 320))
(13, 'relu0_output', 648, (1, 64, 320, 320))
(14, 'pooling0_output', 648, (1, 64, 160, 160))
(15, 'stage1_unit1_bn1_gamma', 648, (64,))
(16, 'stage1_unit1_bn1_beta', 648, (64,))
(17, 'stage1_unit1_bn1_moving_mean', 648, (64,))
(18, 'stage1_unit1_bn1_moving_var', 648, (64,))
(19, 'stage1_unit1_bn1_output', 648, (1, 64, 160, 160))
(20, 'stage1_unit1_relu1_output', 648, (1, 64, 160, 160))
(21, 'stage1_unit1_conv1_weight', 648, (64, 64, 1, 1))
(22, 'stage1_unit1_conv1_output', 648, (1, 64, 160, 160))
(23, 'stage1_unit1_bn2_gamma', 648, (64,))
(24, 'stage1_unit1_bn2_beta', 648, (64,))
(25, 'stage1_unit1_bn2_moving_mean', 648, (64,))
(26, 'stage1_unit1_bn2_moving_var', 648, (64,))
(27, 'stage1_unit1_bn2_output', 648, (1, 64, 160, 160))
(28, 'stage1_unit1_relu2_output', 648, (1, 64, 160, 160))
(29, 'stage1_unit1_conv2_weight', 648, (64, 64, 3, 3))
(30, 'stage1_unit1_conv2_output', 648, (1, 64, 160, 160))
(31, 'stage1_unit1_bn3_gamma', 648, (64,))
(32, 'stage1_unit1_bn3_beta', 648, (64,))
(33, 'stage1_unit1_bn3_moving_mean', 648, (64,))
(34, 'stage1_unit1_bn3_moving_var', 648, (64,))
(35, 'stage1_unit1_bn3_output', 648, (1, 64, 160, 160))
(36, 'stage1_unit1_relu3_output', 648, (1, 64, 160, 160))
(37, 'stage1_unit1_conv3_weight', 648, (256, 64, 1, 1))
(38, 'stage1_unit1_conv3_output', 648, (1, 256, 160, 160))
(39, 'stage1_unit1_sc_weight', 648, (256, 64, 1, 1))
(40, 'stage1_unit1_sc_output', 648, (1, 256, 160, 160))
(41, '_plus0_output', 648, (1, 256, 160, 160))
Traceback (most recent call last):
  File "train.py", line 373, in <module>
    main()
  File "train.py", line 370, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train.py", line 93, in train_net
    sym = eval('get_' + args.network + '_train')(sym)
  File "/home/admin/tools/insightface-master/RetinaFace/rcnn/symbol/symbol_resnet.py", line 409, in get_resnet_train
    return get_sym_train(sym)
  File "/home/admin/tools/insightface-master/RetinaFace/rcnn/symbol/symbol_common.py", line 526, in get_sym_train
    conv_fpn_feat = get_sym_conv(data, sym)
  File "/home/admin/tools/insightface-master/RetinaFace/rcnn/symbol/symbol_common.py", line 207, in get_sym_conv
    stride2layer[stride] = all_layers[name]
  File "/usr/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 518, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "_plus0_output"

**Comment by spy78111** [comment]
@nttstar ，hi,could you help me for this problem

**Comment by faderani** [comment]
I have the same problem... several threads pointing to this problem but still no solution.

**Comment by nttstar** [comment]
You have to change the code... Now fine-tuning can not be done easily.
