### ISSUE TITLE
'test_widerface.py' ---> Help me.....!!!

### ISSUE THREAD

**Issue by Korea-AI** [deepinsight/insightface#1212]
Thanks. Thanks to you, I used 'test.py' usefully.

You are now about to run test_widerface.py. There were a lot of errors, but I'm still working on it.

But there's a big problem.

The 9th line of the 'test_rcnn.py' file is the problem.

Line 9: 'from ..core.loader import TestLoader'

But there is no 'TestLoader' in 'loader.py.'

Help me figure this out.................

**Comment by Korea-AI** [comment]
I solved this problem.
But how do you solve the following error message?

test with Namespace(bbox_vote=True, dataset='retinaface', dataset_path='./data/retinaface', epoch=0, gpu=0, image_set='val', mode=1, network='net3', nocrop=False, output='./wout', part=0, parts=1, prefix='', pyramid=True, root_path='./data', thresh=0.02)
[32, 16, 8] {'32': {'SCALES': (32, 16), 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'ALLOWED_BORDER': 9999}, '16': {'SCALES': (8, 4), 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'ALLOWED_BORDER': 9999}, '8': {'SCALES': (2, 1), 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'ALLOWED_BORDER': 9999}}
INFO:root:Called with argument: Namespace(bbox_vote=True, dataset='retinaface', dataset_path='./data/retinaface', epoch=0, gpu=0, image_set='val', mode=1, network='net3', nocrop=False, output='./wout', part=0, parts=1, prefix='', pyramid=True, root_path='./data', thresh=0.02)
Traceback (most recent call last):
  File "C:/Users/JunPark/win_retina_test/Retinaface-master/Retinaface-master/test_widerface.py", line 197, in <module>
    main()
  File "C:/Users/JunPark/win_retina_test/Retinaface-master/Retinaface-master/test_widerface.py", line 194, in main
    test(args)
  File "C:/Users/JunPark/win_retina_test/Retinaface-master/Retinaface-master/test_widerface.py", line 123, in test
    detector = RetinaFace(args.prefix, args.epoch, args.gpu, network=args.network, nocrop=args.nocrop, vote=args.bbox_vote)
  File "C:\Users\JunPark\win_retina_test\Retinaface-master\Retinaface-master\retinaface.py", line 113, in __init__
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
  File "C:\Users\JunPark\Anaconda3\envs\Jun_Park\lib\site-packages\mxnet\model.py", line 450, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "C:\Users\JunPark\Anaconda3\envs\Jun_Park\lib\site-packages\mxnet\symbol\symbol.py", line 2728, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "C:\Users\JunPark\Anaconda3\envs\Jun_Park\lib\site-packages\mxnet\base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:06:02] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "-symbol.json": No such file or directory

Process finished with exit code 1
