### ISSUE TITLE
ValueError: buffer is smaller than requested size

### ISSUE THREAD

**Issue by meanmee** [deepinsight/insightface#122]
I generate the .rec file use the face2rec2.py, but when i use the generated .rec file to train, it raise an error:

Traceback (most recent call last):
  File "train_softmax.py", line 1104, in <module>
    main()
  File "train_softmax.py", line 1100, in main
    train_net(args)
  File "train_softmax.py", line 1093, in train_net
    epoch_end_callback=checkpoint)
  File "/home/xiaomin.wu/anaconda2/lib/python2.7/site-packages/mxnet-1.0.0-py2.7.egg/mxnet/module/base_module.py", line 482, in fit
    next_data_batch = next(data_iter)
  File "/autofs/data56/xiaomin.wu/code/bitmain/insightface/src/data.py", line 824, in next
    label, s, bbox, landmark = self.next_sample()
  File "/autofs/data56/xiaomin.wu/code/bitmain/insightface/src/data.py", line 750, in next_sample
    header, img = recordio.unpack(s)
  File "/home/xiaomin.wu/anaconda2/lib/python2.7/site-packages/mxnet-1.0.0-py2.7.egg/mxnet/recordio.py", line 370, in unpack
    header = header._replace(label=np.frombuffer(s, np.float32, header.flag))
ValueError: buffer is smaller than requested size

**Comment by nttstar** [comment]
What's the size of your training images?
