### ISSUE TITLE
cant run it

### ISSUE THREAD

**Issue by alicera** [deepinsight/insightface#1271]
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()

I run the arcface
the status still continue,
no message show ,next up

**Comment by anxiangsir** [comment]
You can paste the name of the script you run and the command you run

**Comment by alicera** [comment]
CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r50 --loss arcface --dataset emore
I try to set the default.per_batch_size = 30
the final show the killed

loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
killed

**Comment by alicera** [comment]
mxnet: 1.5.0
command: CUDA_VISIBLE_DEVICES='0' python -u train.py --network r50 --loss arcface --dataset emore
I find the arcface cant use muti-GPU,so I use the 1 GPU

loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
/opt/mxnet/python/mxnet/module/base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.041666666666666664). Is this intended?
  optimizer_params=optimizer_params)
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 374, in main
    train_net(args)
  File "train.py", line 369, in train_net
    epoch_end_callback = epoch_cb )
  File "/opt/mxnet/python/mxnet/module/base_module.py", line 536, in fit
    self.update_metric(eval_metric, data_batch.label, False, data_batch.pad)
  File "/opt/mxnet/python/mxnet/module/module.py", line 777, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced, label_pads)
  File "/opt/mxnet/python/mxnet/module/executor_group.py", line 660, in update_metric
    out.shape[0], islice_batch_size)
AssertionError: output length 1 not a multiple of slice batch_size 24

**Comment by HongliWu** [comment]
I recently came across the same issue when run "**CUDA_VISIBLE_DEVICES='0' python -u train.py --network r100 --loss arcface --dataset emore**".
In my opinion, the cause of this issue is that **the memory of  computer is not enought**.
My computer have 16GB memory. The process is killed when memory is full.

A screenshot of  the runtime:
![2021-06-29 15-39-55屏幕截图](https://user-images.githubusercontent.com/47562735/123757753-e0312580-d8f0-11eb-890e-1e05cb91c2ff.png)

**Comment by HongliWu** [comment]
After I add annother 16GB memory to my computer, **issue solved!**
![2021-06-29 17-31-52屏幕截图](https://user-images.githubusercontent.com/47562735/123778737-001e1480-d904-11eb-8db0-fa27a99ca8ab.png)
