### ISSUE TITLE
when I make a test, MXNetError: cudaMalloc retry failed: out of memory

### ISSUE THREAD

**Issue by fangzong12** [deepinsight/insightface#1341]
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    boxes1, lmds1 = detector.detect(img1, threshold=0.8)
  File "/app/tomcat/bin/executions/7786857/116678/FaceRecog.zip/FaceRecog/model_zoo/face_detection.py", line 341, in detect
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2566, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/superuser/anaconda3/lib/python3.6/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/storage/./pooled_storage_manager.h", line 161
MXNetError: cudaMalloc retry failed: out of memory

**Comment by fangzong12** [comment]
the same error when i use cpu detect face

**Comment by fangzong12** [comment]
the same error when i detect a face with cpu

**Comment by fangzong12** [comment]
mxnet.base.MXNetError: [10:42:33] c:\jenkins\workspace\mxnet-tag\mxnet\src\storage\./cpu_device_storage.h:72: Failed to allocate CPU Memory

**Comment by Saibo-creator** [comment]
Me too
