### ISSUE TITLE
tools onnx2caffe

### ISSUE THREAD

**Issue by thanhdatnv2712** [deepinsight/insightface#1371]
When I run:
`python convertCaffe.py ./model/mmdet.onnx ./model/a.prototxt ./model/a.caffemodel`
I have error:
Traceback (most recent call last):
  File "convertCaffe.py", line 11, in <module>
    import onnx2caffe._operators as cvt
  File "/home/ubuntu/retinafce/02.Codes/insightface/tools/onnx2caffe/onnx2caffe/_operators.py", line 9, in <module>
    from MyCaffe import Function as myf
ModuleNotFoundError: No module named 'MyCaffe'
Help me!

**Comment by nttstar** [comment]
Updated.

**Comment by thanhdatnv2712** [comment]
When I use to convert onnx2caffe
```
Traceback (most recent call last):
  File "convertCaffe.py", line 109, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 67, in convertToCaffe
    print (layer._to_proto())
  File "/home/ubuntu/retinafce/02.Codes/insightface/tools/onnx2caffe/MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "/home/ubuntu/retinafce/02.Codes/insightface/tools/onnx2caffe/MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: upsample_param
```
I have error upsample but README.md: Current support operation have Upsample

**Comment by nttstar** [comment]
You have to add Upsample layer support in your caffe.

**Comment by thanhdatnv2712** [comment]
@nttstar  How to add that layer do you have any instructions? Because I did not see this layer on the homepage of the caffe. Can you send me any tutorial?

**Comment by nttstar** [comment]
google with keyword 'caffe upsample layer'
