### ISSUE TITLE
RuntimeError: simple_bind error. Arguments: data: (1, 3, 112, 112)

### ISSUE THREAD

**Issue by jobbofhe** [deepinsight/insightface#145]
I run the project in a centos7 environment, without GPU, and the Runtime error: simple_bind error.Arguments.bugs. data: 1, 3, 112, 112). Do I need to cut the size ahead of time when loading the custom image?.???

**Comment by nttstar** [comment]
Give more information pls.

**Comment by jobbofhe** [comment]
Thank you so much  help,   and I had found the anwer at #26。

**Comment by KingfaLuis** [comment]
PS D:\code\insightface-master\gender-age> python .\test.py                                                                                                                                                                                   loading model/model 0
[11:50:45] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.3.0. Attempting to upgrade...
[11:50:45] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File ".\test.py", line 17, in <module>
    model = face_model.FaceModel(args)
  File "D:\code\insightface-master\gender-age\face_model.py", line 55, in __init__
    self.model = get_model(ctx, image_size, args.model, 'fc1')
  File "D:\code\insightface-master\gender-age\face_model.py", line 39, in get_model
    model.bind(data_shapes=[('data', (1, 3, image_size[0], image_size[1]))])
  File "d:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "d:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "d:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.py", line 375, in bind_exec
    shared_group))
  File "d:\ProgramData\Anaconda2\lib\site-packages\mxnet\module\executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "d:\ProgramData\Anaconda2\lib\site-packages\mxnet\symbol\symbol.py", line 1629, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
[11:50:45] C:\Jenkins\workspace\mxnet-tag\mxnet\src\storage\storage.cc:119: Compile with USE_CUDA=1 to enable GPU usage

**Comment by tuantran23012000** [comment]
" pip install mxnet-cu101 " for mxnet-cuda version
