### ISSUE TITLE
Error in 'insightface/recognition/tools/mask_renderer.py'

### ISSUE THREAD

**Issue by ygtxr1997** [deepinsight/insightface#1477]
loading ./assets_mask/if1k3d68 0
[20:12:12] ../src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.6.0. Attempting to upgrade...
[20:12:12] ../src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "mask_renderer.py", line 96, in <module>
    tool = MaskRenderer('./assets_mask')
  File "mask_renderer.py", line 28, in __init__
    self.if3d68_handler = Handler(osp.join(model_dir, 'if1k3d68'), 0, 192, ctx_id=0)
  File "/home/yuange/code/SelfServer/DeepInsight/insightface/recognition/tools/image_3d68.py", line 74, in __init__
    ('data', (1, 3, image_size[0], image_size[1]))])
  File "/home/yuange/program/anaconda3/envs/pytorch_1.6.0/lib/python3.6/site-packages/mxnet/module/module.py", line 443, in bind
    for x in self._exec_group.param_arrays
  File "/home/yuange/program/anaconda3/envs/pytorch_1.6.0/lib/python3.6/site-packages/mxnet/module/module.py", line 443, in <listcomp>
    for x in self._exec_group.param_arrays
  File "/home/yuange/program/anaconda3/envs/pytorch_1.6.0/lib/python3.6/site-packages/mxnet/ndarray/utils.py", line 67, in zeros
    return _zeros_ndarray(shape, ctx, dtype, **kwargs)
  File "/home/yuange/program/anaconda3/envs/pytorch_1.6.0/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 4752, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 39, in _zeros
  File "mxnet/cython/ndarray.pyx", line 162, in mxnet._cy3.ndarray._imperative_invoke
TypeError: _imperative_invoke() takes exactly 5 positional arguments (7 given)

**Comment by nttstar** [comment]
mxnet version?

**Comment by ygtxr1997** [comment]
> mxnet version?

Which mxnet version should I use? CUDA version or CPU version? 1.6.0 or later version?

**Comment by ygtxr1997** [comment]
I changed the mxnet version to mxnet-CPU-1.6.0, but the output masked face was incorrect.
Here are the detected landmarks and ouput face:
Link：https://pan.baidu.com/s/1QoMEdhCQVGJUN7m-BNjKtg 
Code：pf5g

**Comment by ygtxr1997** [comment]
The error is caused by 'BFM.mat' and 'BFM_UV.mat'. We should re-generate these two files ourselves.

**Comment by Sihaixianren** [comment]
你是如何重新生成BFM.mat' and 'BFM_UV.mat的？

**Comment by Sihaixianren** [comment]
How did you regenerate BFM. mat and BFM_ UV. mat's?
