### ISSUE TITLE
AssertionError: Assert name is not None

### ISSUE THREAD

**Issue by cserezwan** [deepinsight/insightface#1495]
Hello, I'm getting the following error while I'm trying to train the Retinaface algorithm with the Widerface dataset:

Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 490, in main
    train_net(args,
  File "train.py", line 66, in train_net
    roidbs = [
  File "train.py", line 67, in <listcomp>
    load_gt_roidb(args.dataset,
  File "/home/rh667/Desktop/FP-Projects/insightface-master/detection/RetinaFace/rcnn/utils/load_data.py", line 13, in load_gt_roidb
    imdb = eval(dataset_name)(image_set_name, root_path, dataset_path)
  File "/home/rh667/Desktop/FP-Projects/insightface-master/detection/RetinaFace/rcnn/dataset/retinaface.py", line 42, in __init__
    assert name is not None
AssertionError

Any idea to solve this error?

**Comment by csz-006** [comment]
我也出现这种问题，请问如何解决的

**Comment by csz-006** [comment]
I also have this problem, how to solve it
