### ISSUE TITLE
AssertionError：assert 'detection' in self.models 

### ISSUE THREAD

**Issue by CC-21H** [deepinsight/insightface#1525]
I want to extract 512-D Feature Embedding. I download the pretrained model and run the /insightface/deploy/test.py, but 
![image](https://user-images.githubusercontent.com/44988023/118638371-5b3ef080-b809-11eb-8752-71dda50d4c38.png)
what should I do?

**Comment by 007gzs** [comment]
https://github.com/deepinsight/insightface/blob/master/python-package/README.md

Starting from insightface>=0.2, we use onnxruntime as inference backend, please download our **antelope** model release from [onedrive](https://1drv.ms/u/s!AswpsDO2toNKrU0ydGgDkrHPdJ3m?e=iVgZox), and put it under `~/.insightface/models/`, so there're onnx models at `~/.insightface/models/antelope/*.onnx`.

**Comment by nttstar** [comment]
Please update `insightface` to >=0.2, see readme at [https://github.com/deepinsight/insightface/tree/master/python-package](https://github.com/deepinsight/insightface/tree/master/python-package)

**Comment by CC-21H** [comment]
I have downloaded the antelope  and put it under ~/.insightface/models/. And my insightface version is 0.2.1 （0.2.0 version.I tried, too）.
But the same error is displayed.

![image](https://user-images.githubusercontent.com/44988023/118643584-554c0e00-b80f-11eb-9f99-b64623aa01fb.png)
According to the prompt, I think this line is wrong.

**Comment by 007gzs** [comment]
Please confirm that the file `~/.insightface/models/antelope/scrfd_10g_bnkps.onnx` exists

**Comment by CC-21H** [comment]
![image](https://user-images.githubusercontent.com/44988023/118645186-351d4e80-b811-11eb-852a-fd83d35d359a.png)

**Comment by 007gzs** [comment]
Path is `~/.insightface` not insightface workspace.
You can try `app = FaceAnalysis(name="antelope", root=insightface_workspace_path)`

**Comment by CC-21H** [comment]
It's Ok. Thank you very much.

**Comment by CC-21H** [comment]
How to only extract 512-D Feature Embedding. I have the extracted face image, don't need to detection.

And I directly test my picture, the model can't detect it. The `len(faces)` is 0.

**Comment by nttstar** [comment]
model = insightface.model_zoo.ArcFaceONNX(model_file = xxx)

**Comment by CC-21H** [comment]
![Uploading image.png…]()

**Comment by nttstar** [comment]
where's your last post?

**Comment by CC-21H** [comment]
> ![image](https://user-images.githubusercontent.com/44988023/118786021-02805e00-b8c4-11eb-996e-305d40b683d9.png)
> My image size is (147,117,3)

This is my last post. My code is 
![image](https://user-images.githubusercontent.com/44988023/118786863-cf8a9a00-b8c4-11eb-9a0a-2cd75c2b58d7.png)

**Comment by 007gzs** [comment]
detect and face_align first

**Comment by CC-21H** [comment]
I just want to extract  Feature Embedding. I have extracted face, don't need to detect and face_align.

**Comment by 007gzs** [comment]
in arcface, face image size mast 112x112

**Comment by nadaboulares** [comment]
how did u correct this

**Comment by nadaboulares** [comment]
help plz

**Comment by nhatduy19599** [comment]
i also had the same problem when running the executable.
Error displayed: Exception has occurred: AssertionError
exception: no description
  File "E:\DataTraining\insightface-master\insightface-master\deploy\test.py", line 16, in <module>
    app = FaceAnalysis(name='antelope')
-----------------
i have followed the suggestions above but its still not fixed, what should i do?
thanks

**Comment by nttstar** [comment]
you can change your root directory. I don't know if the path like '~/.insightface' can work well on windows os.

**Comment by nhatduy19599** [comment]
> you can change your root directory. I don't know if the path like '~/.insightface' can work well on windows os.
---------
I've tried it but still can't fix that error. "antelope" still exists in models but I still don't know why it doesn't work.
When running terminal with command :python test.py
the results give:
 E:\DataTraining\insightface-master\insightface-master\deploy> python test.py
Traceback (most recent call last):
  File "test.py", line 22, print <module>
    app = FaceAnalysis('antelope')
  File "C:\Users\nhatd\AppData\Local\Programs\Python\Python36\lib\site-packages\insightface\app\face_analysis.py", line 51, print __init__
    assert 'detection' in self.models
AssertionError
--------------
I have tried many ways like changing face_analyst.py file in python36 and also face_analyst.py in python-package belonging to source ROOT $insightface but the result is not very satisfactor

**Comment by okoliechykwuka** [comment]
On Windows, replace the **root** parameter in the FaceAnalysis Class with the complete or absolute path to the **insightface** folder. remember to create a model folder and place the **onnx  model ** in it.

`e.g root=r'C:\Users\OneDrive\Desktop\insight\insightface\Lib\site-packages\insightface'`

onnx  model  path will be .

`r'C:\Users\OneDrive\Desktop\insight\insightface\Lib\site-packages\insightface\model\antelope\*.onnx`

**Comment by ychess** [comment]
我说一下我的解决方法给各位参考，我发现comfyui在安装该插件时，在https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip处下载了文件到“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\”这个目录下，然后进行解压安装，解压后的路径是“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2\”，然后我将这个路径下的文件全部剪切到了“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\”这里，然后重启就正常了。说明在软件进行解压时，多了一层目录导致。

I'd like to share my solution for your reference. I noticed that when installing the plugin in ComfyUI, it downloaded a file from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip to the directory "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models" and then proceeded with the extraction and installation. After extraction, the path was "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2". Then, I cut all the files from this path and pasted them into "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2". After restarting, it worked normally. This indicates that during the software's extraction process, an extra directory layer was created, causing the issue.

**Comment by mrhan1993** [comment]
> 我说一下我的解决方法给各位参考，我发现comfyui在安装该插件时，在[https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip处下载了文件到“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\”这个目录下，然后进行解压安装，解压后的路径是“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2\”，然后我将这个路径下的文件全部剪切到了“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\”这里，然后重启就正常了。说明在软件进行解压时，多了一层目录导致。](https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip%E5%A4%84%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%96%87%E4%BB%B6%E5%88%B0%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5C%E2%80%9D%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E4%B8%8B%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E5%AE%89%E8%A3%85%EF%BC%8C%E8%A7%A3%E5%8E%8B%E5%90%8E%E7%9A%84%E8%B7%AF%E5%BE%84%E6%98%AF%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5Cantelopev2%5C%E2%80%9D%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E5%B0%86%E8%BF%99%E4%B8%AA%E8%B7%AF%E5%BE%84%E4%B8%8B%E7%9A%84%E6%96%87%E4%BB%B6%E5%85%A8%E9%83%A8%E5%89%AA%E5%88%87%E5%88%B0%E4%BA%86%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5C%E2%80%9D%E8%BF%99%E9%87%8C%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E5%90%AF%E5%B0%B1%E6%AD%A3%E5%B8%B8%E4%BA%86%E3%80%82%E8%AF%B4%E6%98%8E%E5%9C%A8%E8%BD%AF%E4%BB%B6%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E6%97%B6%EF%BC%8C%E5%A4%9A%E4%BA%86%E4%B8%80%E5%B1%82%E7%9B%AE%E5%BD%95%E5%AF%BC%E8%87%B4%E3%80%82)
> 
> 我说一下我的解决方法给各位参考，我发现comfyui在安装该插件时，在[https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip处下载了文件到“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\”这个目录下，然后进行解压安装，解压后的路径是“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2\”，然后我将这个路径下的文件全部剪切到了“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\”这里，然后重启就正常了。说明在软件进行解压时，多了一层目录导致。](https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip%E5%A4%84%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%96%87%E4%BB%B6%E5%88%B0%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5C%E2%80%9D%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E4%B8%8B%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E5%AE%89%E8%A3%85%EF%BC%8C%E8%A7%A3%E5%8E%8B%E5%90%8E%E7%9A%84%E8%B7%AF%E5%BE%84%E6%98%AF%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5Cantelopev2%5C%E2%80%9D%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E5%B0%86%E8%BF%99%E4%B8%AA%E8%B7%AF%E5%BE%84%E4%B8%8B%E7%9A%84%E6%96%87%E4%BB%B6%E5%85%A8%E9%83%A8%E5%89%AA%E5%88%87%E5%88%B0%E4%BA%86%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5C%E2%80%9D%E8%BF%99%E9%87%8C%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E5%90%AF%E5%B0%B1%E6%AD%A3%E5%B8%B8%E4%BA%86%E3%80%82%E8%AF%B4%E6%98%8E%E5%9C%A8%E8%BD%AF%E4%BB%B6%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E6%97%B6%EF%BC%8C%E5%A4%9A%E4%BA%86%E4%B8%80%E5%B1%82%E7%9B%AE%E5%BD%95%E5%AF%BC%E8%87%B4%E3%80%82)
> 
> I'd like to share my solution for your reference. I noticed that when installing the plugin in ComfyUI, it downloaded a file from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip to the directory "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models" and then proceeded with the extraction and installation. After extraction, the path was "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2". Then, I cut all the files from this path and pasted them into "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2". After restarting, it worked normally. This indicates that during the software's extraction process, an extra directory layer was created, causing the issue.
> 
> 我想分享一下我的解决方案，供大家参考。我注意到，在ComfyUI中安装插件时，它从https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip下载了一个文件到目录“D：\AITools\ComfyUI-aki-v1.4\模型\洞察面\模型”，然后进行提取和安装。提取后，路径为“D：\AITools\ComfyUI-aki-v1.4\模型\洞察面\模型\antelopev2”。然后，我从这个路径中剪切了所有文件，并将它们粘贴到“D：\AITools\ComfyUI-aki-v1.4\模型\洞察面\模型\antelopev2”中。重新启动后，它正常工作。这表明在软件的提取过程中，创建了一个额外的目录层，导致了问题。

is work for me

**Comment by Leonel0727** [comment]
@ychess 
thank for help, i face this issue just now, your solution is helpful

Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Music\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by aminesoulaymani** [comment]
I solved this problem, comfyui automatically downloaded and put the *.onnx inside antelopev2/antelopev2/*.onnx.
Move the onnx files into the parent folder: antelopev2/*.onnx

**Comment by sancelot** [comment]
On my windows system, altough files have been downloaded, it does not find them, since it does not look in the right folder

in face_analysis.py file, replace         

onnx_files = glob.glob(osp.join(self.model_dir, '*.onnx'))

with 
        onnx_files = [osp.join(dirpath, f)
            for dirpath, dirnames, files in os.walk(self.model_dir)
            for f in fnmatch.filter(files, '*.onnx')] 

and add at the file beginning:
import os
import fnmatch

**Comment by MATEMATNKx** [comment]
When you first run code you have download onnx models
```
app = FaceAnalysis(name='antelopev2', root=".\onnx_models", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'], allowed_modules=['detection'])
```
but model download as
![image](https://github.com/user-attachments/assets/8646ad2c-b8bd-4ef0-92e8-59ce3e87c5f3)
if you would run project more then 2 time 
change `antelopev2` to `antelopev2/antelopev2`
```
app = FaceAnalysis(name='antelopev2/antelopev2', root=".\onnx_models", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'], allowed_modules=['detection'])
```

**Comment by CaledoniaProject** [comment]
I changed model to `buffalo_l` and the error is gone.

**Comment by MATEMATNKx** [comment]
> > I solved this problem, comfyui automatically downloaded and put the _.onnx inside antelopev2/antelopev2/_.onnx. Move the onnx files into the parent folder: antelopev2/*.onnx
> 
> can't believe after all these years no one fix it

this is a default file unzipping issue. The code may have been tested on Linux/macos, but not on windows

Fixing the code helps to fix the error
https://github.com/deepinsight/insightface/issues/2702

**Comment by liuziangexit** [comment]
> > > I solved this problem, comfyui automatically downloaded and put the _.onnx inside antelopev2/antelopev2/_.onnx. Move the onnx files into the parent folder: antelopev2/*.onnx
> > 
> > 
> > can't believe after all these years no one fix it
> 
> this is a default file unzipping issue. The code may have been tested on Linux/macos, but not on windows
> 
> Fixing the code helps to fix the error [#2702](https://github.com/deepinsight/insightface/issues/2702)

thanks for quick reply and thank you for all you did, but what i mean is I can't believe they haven't merged fixes like yours after all these years----this issue was opened back in 2021. 
and btw in fact it's not a Windows-only issue, i encountered this on my mac, and i assume we can also have this on linux.

**Comment by CoderSuHang** [comment]
> 我说一下我的解决方法给各位参考，我发现comfyui在安装该插件时，在[https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip处下载了文件到“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\”这个目录下，然后进行解压安装，解压后的路径是“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2\”，然后我将这个路径下的文件全部剪切到了“D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\”这里，然后重启就正常了。说明在软件进行解压时，多了一层目录导致。](https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip%E5%A4%84%E4%B8%8B%E8%BD%BD%E4%BA%86%E6%96%87%E4%BB%B6%E5%88%B0%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5C%E2%80%9D%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%BD%95%E4%B8%8B%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E5%AE%89%E8%A3%85%EF%BC%8C%E8%A7%A3%E5%8E%8B%E5%90%8E%E7%9A%84%E8%B7%AF%E5%BE%84%E6%98%AF%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5Cantelopev2%5C%E2%80%9D%EF%BC%8C%E7%84%B6%E5%90%8E%E6%88%91%E5%B0%86%E8%BF%99%E4%B8%AA%E8%B7%AF%E5%BE%84%E4%B8%8B%E7%9A%84%E6%96%87%E4%BB%B6%E5%85%A8%E9%83%A8%E5%89%AA%E5%88%87%E5%88%B0%E4%BA%86%E2%80%9CD:%5CAITools%5CComfyUI-aki-v1.4%5Cmodels%5Cinsightface%5Cmodels%5Cantelopev2%5C%E2%80%9D%E8%BF%99%E9%87%8C%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E5%90%AF%E5%B0%B1%E6%AD%A3%E5%B8%B8%E4%BA%86%E3%80%82%E8%AF%B4%E6%98%8E%E5%9C%A8%E8%BD%AF%E4%BB%B6%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%8E%8B%E6%97%B6%EF%BC%8C%E5%A4%9A%E4%BA%86%E4%B8%80%E5%B1%82%E7%9B%AE%E5%BD%95%E5%AF%BC%E8%87%B4%E3%80%82)
> 
> I'd like to share my solution for your reference. I noticed that when installing the plugin in ComfyUI, it downloaded a file from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip to the directory "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models" and then proceeded with the extraction and installation. After extraction, the path was "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2\antelopev2". Then, I cut all the files from this path and pasted them into "D:\AITools\ComfyUI-aki-v1.4\models\insightface\models\antelopev2". After restarting, it worked normally. This indicates that during the software's extraction process, an extra directory layer was created, causing the issue.

very good! Thx!

**Comment by CoderSuHang** [comment]
您好，我是苏航，感谢您的来信！我会尽快对来信进行查看并尽快给您进行回复，祝您身体健康，工作顺利，谢谢！

**Comment by zzdrill** [comment]
> When you first run code you have download onnx models
> 
> ```
> app = FaceAnalysis(name='antelopev2', root=".\onnx_models", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'], allowed_modules=['detection'])
> ```
> 
> but model download as ![image](https://github.com/user-attachments/assets/8646ad2c-b8bd-4ef0-92e8-59ce3e87c5f3) if you would run project more then 2 time change `antelopev2` to `antelopev2/antelopev2`
> 
> ```
> app = FaceAnalysis(name='antelopev2/antelopev2', root=".\onnx_models", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'], allowed_modules=['detection'])
> ```
> 
> This problem is related to unpacking the zip archive

CORRECT ANSWER！

**Comment by CoderSuHang** [comment]
您好，我是苏航，感谢您的来信！我会尽快对来信进行查看并尽快给您进行回复，祝您身体健康，工作顺利，谢谢！
