### ISSUE TITLE
Im testing scrfd but they dont find the key

### ISSUE THREAD

**Issue by knydr622** [deepinsight/insightface#1547]
Hi, I am test "webcam_demo.py" in insightface/scrfd.
However, I could not do it cuz 

"" KeyError: 'SCRFD is not in the models registry ""

Im using pre-trained model ::
configs/scrfd/SCRFD_2.5G_BNKPS.py
checkpoints/SCRFD_2.5G_KPS.pth

I can find how to do. Can u help me ??
Thanks

**Comment by nttstar** [comment]
right now just use tools/scrfd.py for inference.

**Comment by knydr622** [comment]
Hi, thanks for ur reply

However I face another problem ::
Traceback (most recent call last):
  File "tools/scrfd.py", line 326, in <module>
    detector = SCRFD(model_file='./det.onnx')
  File "tools/scrfd.py", line 80, in __init__
    assert osp.exists(self.model_file)
AssertionError

Also, if I run 'scrfd2onnx.py, there are not (build_model_from_cfg, generate_inputs_and_wrap_model, preprocess_example_input) and onnxsim.

Plz help. Im suffered abt a week  
Thanks

**Comment by ignacioserna** [comment]
Hi, you have to install the insightface repository.

**Comment by leoluopy** [comment]
install mmdet at scrfd root diretory , problem is solved
`pip install -v -e .  # or "python setup.py develop"`
@knydr622
