### ISSUE TITLE
[MFR21] ICCV21 masked face recognition challenge discussion

### ISSUE THREAD

**Issue by nttstar** [deepinsight/insightface#1564]
How to participate:

[https://github.com/deepinsight/insightface/tree/master/challenges/iccv21-mfr](https://github.com/deepinsight/insightface/tree/master/challenges/iccv21-mfr)

Submission server:
http://iccv21-mfr.com/

Workshop homepage:
https://ibug.doc.ic.ac.uk/resources/masked-face-recognition-challenge-workshop-iccv-21/

Any issue can be left in this thread.

**Comment by huanghanmei** [comment]
有谁测试过baseline 模型在IJBC上的准确率吗？我测试时一直报错。

**Comment by vuvko** [comment]
Hello and thank you for organizing the challenge this year!
In your rules, you prohibit the use of pre-trained models and any external data, but there is no mention of how you'd enforce this rule. Will you demand training pipelines and cooperation to reproduce the results from top teams?

**Comment by nttstar** [comment]
@vuvko Yes, top-rank players should send their solutions to organizers after submission closed.

**Comment by vuvko** [comment]
Thank you for your quick response! 
Will you check the reproducibility of the training pipeline? If so, what will you do in case of a different result model (it can be hardware-dependent)?

**Comment by nttstar** [comment]
@vuvko We will strictly check the reproducibility. There should not be any hardware-dependent issue.

**Comment by anxiangsir** [comment]
> 有谁测试过baseline 模型在IJBC上的准确率吗？我测试时一直报错。

Please join the QQ group or WeChat group, let’s talk in detail.

**Comment by manideep2510** [comment]
Hi
Uploading the model on the submission page is very very slow. I have checked my internet connection and it is good with an upload speed greater than 25 MB/s. Upload to the [submission portal](http://iccv21-mfr.com/comp/#/submit) is happening at <50 KB/s speed.
Can someone please help me with this?

**Comment by vuvko** [comment]
Same problem here, I cannot upload the baseline iresnet50 model due to very slow upload speed.

**Comment by manideep2510** [comment]
Now, the speed is less than 10 KB/sec. @nttstar Can you please look into this?
Thanks in advance 🙂

**Comment by nttstar** [comment]
@manideep2510 @vuvko The submission server is located in China and it seems to have bandwidth problems for other countries. We will try to find a solution soon.

**Comment by nutsam** [comment]
Is there any preprocessing like normalization before load to model ? 
[iccv21-mfr](https://github.com/deepinsight/insightface/tree/master/challenges/iccv21-mfr) only mentioned that
the input shape should equal to 3x112x112 (RGB order)

**Comment by nttstar** [comment]
@nutsam Normalization setting will be auto-detected in our onnx_helper.py, please check it.

**Comment by muncok** [comment]
Hello,

The status of my submission is still "Running" for 24hours.

Is it a possible case? or any problem with that?

My user name is "Euler".

Thank  you!

**Comment by dmonterom** [comment]
Hi, although I have not submitted any algorithm yet, it always says: "Today, you have submitted 3 times, 0 remaining."
I have tried it using chrome and firefox. My username is dmonterom.

Thanks in advance!

**Comment by vuvko** [comment]
@nttstar is there any update on the uploading problem?

**Comment by nttstar** [comment]
@vuvko We're trying!

**Comment by nttstar** [comment]
@nqkhai1706 Have you checked with onnxruntime==1.6 ?

**Comment by nqkhai1706** [comment]
> @nqkhai1706 Have you checked with onnxruntime==1.6 ?

No, my onnxruntime version: 1.8.0.
May it different on 1.6?
I will check it.
Thank you,

**Comment by nqkhai1706** [comment]
@nttstar I have checked again with onnxruntime==1.6, the result is same with onnxruntume==1.8.0.
Do you have any other idea why my model got error on your side?
Thank you,

**Comment by anxiangsir** [comment]
> @nttstar I have checked again with onnxruntime==1.6, the result is same with onnxruntume==1.8.0.
> Do you have any other idea why my model got error on your side?
> Thank you,

This is our error:

```shell
>>> import onnxruntime
>>> session = onnxruntime.InferenceSession("ms1m_groupface_resnet101.onnx",  None)                                                                                                                      Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/face/miniconda3/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/face/miniconda3/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 226, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /mnt/data/models/1624534624858999668/ms1m_groupface_resnet101.onnx failed:Protobuf parsing failed.
```

The environment of our system is as follows:

```shell
Driver Version: 450.80.02
Cuda compilation tools, release 10.2, V10.2.89
onnx==1.8.0
onnx-simplifier==0.3.5
onnxoptimizer==0.2.5
onnxruntime-gpu==1.6.0
```

**Comment by zhanglaplace** [comment]
测试的时候能否知道当前的图片是否有mask

**Comment by manideep2510** [comment]
@nttstar Even though I have not submitted any model today or yesterday. The portal is still showing that 
```
Today, you have submitted 3 times, 0 remaining.
```

Can you please look into this? Thanks in advance.

**Comment by nttstar** [comment]
@manideep2510 What is your username?

**Comment by nttstar** [comment]
> 测试的时候能否知道当前的图片是否有mask

@zhanglaplace 目前不能

**Comment by manideep2510** [comment]
> @manideep2510 What is your username?

My user name is `sherlock`.

**Comment by anxiangsir** [comment]
> @nttstar Even though I have not submitted any model today or yesterday. The portal is still showing that
> 
> ```
> Today, you have submitted 3 times, 0 remaining.
> ```
> 
> Can you please look into this? Thanks in advance.

It's probably a bug about jet lag, and we'll fix that in a second.

**Comment by JesseEisen** [comment]
> @nttstar Even though I have not submitted any model today or yesterday. The portal is still showing that
> 
> ```
> Today, you have submitted 3 times, 0 remaining.
> ```
> 
> Can you please look into this? Thanks in advance.

Hi, please provide some information related to the browser to help better debug. Like which browser you use and the version of the browser.

**Comment by nttstar** [comment]
@manideep2510 Hi, @JesseEisen is helping us build the evaluation system, please let him know your detailed issue.

**Comment by manideep2510** [comment]
I am using Mozilla Firefox Version 89.02. The portal is now showing 
```
Today, you have submitted 8 times, -5 remaining.
```
But I am able to upload and make submissions.

**Comment by nttstar** [comment]
@manideep2510 Can you try Chrome?

**Comment by manideep2510** [comment]
Yeah, exact same thing is happening on chrome as well.

**Comment by nttstar** [comment]
@vuvko @manideep2510 You can try the link of http://124.156.136.55/ , to see if it is faster.

**Comment by vuvko** [comment]
@nttstar The speed is not great (around 700Kb/s), but I could at least submit a model through that link. Thank you!

**Comment by champagne828** [comment]
hello, could u plz update the qr code of wechat group? it has expired. thx!

**Comment by anxiangsir** [comment]
> hello, could u plz update the qr code of wechat group? it has expired. thx!

add my wechat: `anxiangsir`

**Comment by nttstar** [comment]
@champagne828 Updated

**Comment by muncok** [comment]
Would you please add an editable column in the "Submissions" page?

It would be very helpful to remember the configuration of each submission.

**Comment by nqkhai1706** [comment]
Hello everybody,
Sorry if I bother you. I am participating on MS1MV3 challenge. I am very surprised to see a lot of teams passed the baseline with a very large margin: ~89 on ALL column (as my knowledge, ArcFace with partial_fc is a SOTA method).

I have tuned a lot of tricks, but the score is still low. If you are in same situation with me, can we share a bit about needed tricks for the challenge? For that, we can learn together and improve our knowledge.
Thank you and you have a nice day,

**Comment by powermano** [comment]
test script runtime error?  Something wrong with my submit model?

**Comment by John1231983** [comment]
What does it mean tab "unconstrained" (beside ms1m and glint360k). Does it mean we can use external data and more larger model?

**Comment by anxiangsir** [comment]
> What does it mean tab "unconstrained" (beside ms1m and glint360k). Does it mean we can use external data and more larger model?

yes

**Comment by John1231983** [comment]
I cannot find the information in web page. Could you announce about "unconstrained" tab?

**Comment by nttstar** [comment]
@John1231983 It is not official track of iccv21-mfr

**Comment by ABD-01** [comment]
Is there something else that also needs to be done after `sign up` ??
I'm always getting the message: ```Your account is not actived```

**Comment by ABD-01** [comment]
Hi, for `ms1m` track we are required to train onnx model on this [dataset (MS1M-RetinaFace)](https://github.com/deepinsight/insightface/blob/master/recognition/_datasets_/README.md#ms1m-retinaface) right?

**Comment by nttstar** [comment]
@ABD-01 Right

**Comment by John1231983** [comment]
Does the submission still available and allow to submit after deadline?

**Comment by nttstar** [comment]
Yes, and we will also add LFW/CFP/AGEDB/IJBC/MegaFace benchmarks.

**Comment by John1231983** [comment]
@nttstar "1 October - Stop leader-board submission (11:59 PM Pacific Time)"
Does it mean the score will not update on leaderboard but the user still can see score in the own submission page?

**Comment by nttstar** [comment]
@John1231983 Users can select which scores to be shown on the leaderboard after submission closed for 1 or 2 days.

**Comment by John1231983** [comment]
Do you have plan to upload workshop video to youtube?

**Comment by ygtxr1997** [comment]
Could you provide the testing dataset?

**Comment by guijuzhejiang** [comment]
能分享一些技巧和思路吗？

**Comment by jacqueline-weng** [comment]
![image](https://user-images.githubusercontent.com/62649623/157029810-485091fb-625c-46cd-bd0a-78256c5e7950.png)
My model has passed the check_onnx.py in local environmnet with cuda10.2, onnx1.6.0, ort1.8.0 but failed the test.
Could you give more clues about what is going on?
Thank you in advance.

**Comment by v-trungdt21** [comment]
Can anybody update the link for the non-China user? I can't access it and submit via the iccv-mfr website is desperately slow for me in this region :(

**Comment by beingjoey** [comment]
I can not sign up MFR ongo. Is there any other server?

**Comment by nttstar** [comment]
@beingjoey We're upgrading the whole system, please wait for 1-2 days.

**Comment by JackLin-Authme** [comment]
I have some problem on testing my model with onnx_helper.py
It's seems that `self.providers = None` would be broken when using onnxruntime-gpu>=1.9.0

**Comment by nttstar** [comment]
@JesseEisen No such problem in our system.

**Comment by jovialio** [comment]
Hi i would like to benchmark my model against the MFR dataset and have registered via http://iccv21-mfr.com/#/login. Is the sign up still valid? Have not receive replies.

**Comment by nttstar** [comment]
@jovialio what is your username?

**Comment by HaoLiuHust** [comment]
减均值除方差的操作是由模型做还是测试时会做？

**Comment by nttstar** [comment]
如果onnx模型前几层有Sub Div类似的操作会被自动监测到，这样测试代码不会做额外mean std处理。否则会采用默认的mean=127.5, std=127.5。 @HaoLiuHust

**Comment by hyperf0cus** [comment]
Trained with arcface_torch MobileFaceNet MFN model, converted via torch2onnx.py can't pass onnx_parser.py, and obviously can't pass submission on MFR challenge... 
evaluation tool MFR failed: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'MatMul_95' Status Message: matmul_helper.h:57 Compute MatMul dimension mismatch
I didn't change architecture, structure, layers inside backbones mobilefacenet, but error happens...

**Comment by abdu-khamd** [comment]
@nttstar I am also having problems with uploading my model. It passed onnx_helper.py. However, when submitting to the server I get this error `evaluation tool MFR failed: load onnx failed`.

**Comment by nttstar** [comment]
@hyperf0cus @abdu-khamd Make sure the onnxruntime-gpu version in your test env matches our guide.

**Comment by thNam98** [comment]
Hi @nttstar , i would like to benchmark my model against the MFR dataset and have registered user. But always received "user unconfirmed after register". Can you check again for me, thanks!

**Comment by Cevikalp** [comment]
Hello, I would like to benchmark my model against the MFR dataset and have registered via http://iccv21-mfr.com/#/login. Is the sign up still valid? I did not receive any confirmation email.

**Comment by amoonfana** [comment]
Hi, it seems new registering via http://iccv21-mfr.com/#/login is not available anymore. Is there any way if we want to test our face recognition method on MFR?

**Comment by Cevikalp** [comment]
Hello,
We uploaded our model to the server but it is written that "evaluation tool
MIV failed: max feat dim exceed, given 12500". Our method returns 12500
dimensional features and there is no way to decrease it. We submitted  a
paper to IEEE Transactions on Neural networks and one reviewer insisted on
testing our method on this challenge. Could you test our method and share
the results with us please? You do not need to report our results on the
MFR site.
Best regards,
Prof. Hakan Cevikalp

**Comment by nttstar** [comment]
@Cevikalp Sorry we don't support the model evaluation with such high feature dimension.

**Comment by Cevikalp** [comment]
Hi Hakan，

Let me check the evaluation server status and get back to you shortly.

Best regards,
Jiankang
________________________________

**Comment by Cevikalp** [comment]
Thank you very much.

31 Mar 2024 Pzr 00:55 tarihinde Deng, Jiankang ***@***.***>
şunu yazdı:

> Hi Hakan，
>
> Let me check the evaluation server status and get back to you shortly.
>
> Best regards,
> Jiankang
> ------------------------------
> *From:* Hakan Cevikalp ***@***.***>
> *Sent:* 30 March 2024 13:45
> *To:* deepinsight/insightface <
> ***@***.***>;
> ***@***.*** ***@***.***>; Deng, Jiankang <
> ***@***.***>; ***@***.*** <
> ***@***.***>; Jiwen Lu ***@***.***>;
> ***@***.*** ***@***.***>;
> ***@***.*** ***@***.***>
> *Cc:* deepinsight/insightface ***@***.***>; Comment <
> ***@***.***>
> *Subject:* Re: [deepinsight/insightface] [MFR21] ICCV21 masked face
> recognition challenge discussion (#1564)
>
>
> This email from ***@***.*** originates from outside
> Imperial. Do not click on links and attachments unless you recognise the
> sender. If you trust the sender, add them to your safe senders list
> <https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email
> stamping for this address.
>
>
> Hello,
> We uploaded our model to the server but it is written that "evaluation
> tool MIV failed: max feat dim exceed, given 12500". Our method returns
> 12500 dimensional features and there is no way to decrease it. We submitted
>  a paper to IEEE Transactions on Neural networks and one reviewer insisted
> on testing our method on this challenge. Could you test our method and
> share the results with us please? You do not need to report our results on
> the MFR site.
> Best regards,
> Prof. Hakan Cevikalp
>

**Comment by juechengxi** [comment]
您好，我想根据 MFR 数据集对我的模型进行基准测试，但没有收到任何确认电子邮件，能批准一下新注册吗？

**Comment by hewei011224** [comment]
您好，我想参加 MFR-Ongoing，注册后没有收到任何确认电子邮件，能批准一下新注册吗？

**Comment by HYL-Dave** [comment]
@nttstar 你好，你们提供的 vit-l 代码训练出来就超过了 1 GB，无法上传测试，请问用什么方式可以 upload 测试？

**Comment by onnx20** [comment]
> I have approved all new registrations.

@nttstar Please request registration of MFR, username: koala, Thanks.

**Comment by nttstar** [comment]
> 您好，我想参加 MFR-Ongoing，注册后没有收到任何确认电子邮件，能批准一下新注册吗？

已通过

**Comment by nttstar** [comment]
> > I have approved all new registrations.
> 
> @nttstar Please request registration of MFR, username: koala, Thanks.

DONE

**Comment by sssssshf** [comment]
> > > I have approved all new registrations.
> > 
> > 
> > @nttstar Please request registration of MFR, username: koala, Thanks.
> 
> DONE

您好我再使用mbf作为backbone训练的人脸识别模型  送到mfr进行测试是报错如下：
![image](https://github.com/deepinsight/insightface/assets/68574922/cff8e5d1-16f7-4075-9cdf-ba68876eb1c3)
我用r100送入评测能够得出结果，并且两份模型的转onnx代码一致 嘛烦指导一下如何解决这个问题

**Comment by Xuqt1120** [comment]
你好，请问MFR-Ongoing中的LFW, CFP-FP, AgeDB-30 和 MS1MV3压缩包中的LFW, CFP-FP, AgeDB-30有没有什么区别呢，我使用verification.py测试模型在MS1MV3压缩包中的LFW, CFP-FP, AgeDB30的性能，比较结果发现：
MS1MV3压缩包中的LFW, CFP-FP的结果要远优于MFR-Ongoing的结果，AgeDB大部分情况结果相同，少数MS1MV3压缩包的结果略优于MFR-Ongoing的结果
是否MFR-Ongoing在MS1MV3基础上做了 移除重复身份图片 或其他操作呢，或者是MFR-Ongoing测试流程与verification.py不同？

**Comment by Xuqt1120** [comment]
你好，请问MFR-Ongoing中的LFW, CFP-FP, AgeDB-30 和 MS1MV3压缩包中的LFW, CFP-FP, AgeDB-30有没有什么区别呢，我使用verification.py测试模型在MS1MV3压缩包中的LFW, CFP-FP, AgeDB30的性能，比较结果发现：
MS1MV3压缩包中的LFW, CFP-FP的结果要远优于MFR-Ongoing的结果，AgeDB大部分情况结果相同，少数MS1MV3压缩包的结果略优于MFR-Ongoing的结果
是否MFR-Ongoing在MS1MV3基础上做了 移除重复身份图片 或其他操作呢，或者是MFR-Ongoing测试流程与verification.py不同？

**Comment by HustTD** [comment]
@nttstar Can you approve my registration? username: v.thanhtm6@vinbigdata.com, Thanks.

**Comment by nttstar** [comment]
@HustTD Done

**Comment by livermoressss** [comment]
@nttstar Could you approve my registration? username: sun8878232@gmail.com. Thanks

**Comment by nttstar** [comment]
> @nttstar Could you approve my registration? username: [sun8878232@gmail.com](mailto:sun8878232@gmail.com). Thanks

@livermoressss done

**Comment by MSRCZW** [comment]
@nttstar Could you approve my registration? username: chenzw. Thanks

**Comment by nttstar** [comment]
> @nttstar Could you approve my registration? username: chenzw. Thanks

@MSRCZW done

**Comment by 20144115** [comment]
@nttstar Could you approve my registration? username: tom_hust. Thanks

**Comment by harikiran17** [comment]
@nttstar Could you approve my registration? username: harikiran
Thanks

**Comment by satvikkaurav** [comment]
@nttstar Could you please approve my registration? username: satvik

**Comment by nttstar** [comment]
@20144115 @harikiran17 @satvikkaurav Done

**Comment by TranThanh96** [comment]
@nttstar what is wrong with your server? http://iccv21-mfr.com/ keep spinning

**Comment by nttstar** [comment]
@TranThanh96 Restarted, you can try again.

**Comment by Eliza-and-black** [comment]
您好，我想根据 MFR 数据集对我的模型进行基准测试，但没有收到任何确认电子邮件，能批准一下新注册吗？

**Comment by Eliza-and-black** [comment]
@nttstar Could you approve my registration? username: ymd. Thanks

**Comment by nttstar** [comment]
> @nttstar Could you approve my registration? username: ymd. Thanks

@Eliza-and-black Done

**Comment by zhangxueyuan2017** [comment]
@nttstar Could you please approve my registration? username: xyz   Thanks

**Comment by nttstar** [comment]
> @nttstar Could you please approve my registration? username: xyz Thanks

@zhangxueyuan2017 Done

**Comment by TranThanh96** [comment]
@nttstar I think the server is hanging. I submitted a model two days ago, and it is still in the waiting step. Can you take a look?

![Image](https://github.com/user-attachments/assets/bb8e910c-8f7c-44aa-911f-f750e469ef42)

**Comment by nttstar** [comment]
@TranThanh96 Due to GPU resource constraints, we are temporarily taking this service offline. If any companies or individuals are interested in hosting this service, please contact me via email: ``guojia AT insightface.ai``

**Comment by DJLee68** [comment]
@nttstar 你好，我无法访问这个登录网站，你能帮我检查一下吗？我现在在国外留学，不在中国，是因为这个原因无法登录吗？

**Comment by HYL-Dave** [comment]
@nttstar How many GPUs and other hardware resources are required to deploy this service?

**Comment by TranThanh96** [comment]
@nttstar  can you public scoreboard iccv21-mfr only ? just disable new submition

**Comment by TranThanh96** [comment]
Hi team,
Do you have any plans to reopen this service? @nttstar

**Comment by WakingHours-GitHub** [comment]
As of now, it is still not possible to test the model. So now, nobody can test their models on MFR test datasets? I want to know when it will recover.
