### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by faisalshahbaz** [deepinsight/insightface#1565]
Hello,

I got an error in insightface package of retinaFace. 

```
import insightface
model = insightface.model_zoo.get_model('retinaface_r50_v1')
model.prepare(ctx_id=-1, nms=0.4)
```

error:

AttributeError: 'NoneType' object has no attribute 'prepare'

**Comment by lz381** [comment]
I had the same problem - `get_model` doesn't seem to be throwing the error when downloading the model. 

I fixed it by manually downloading the models and copying them over to the specified folder as detailed [here](https://github.com/deepinsight/insightface/tree/master/python-package).

**Comment by Hwijune** [comment]
```
~/insightface/alignment/coordinateReg$ python3 image_infer.py
loading ./model/2d106det 0
Traceback (most recent call last):
  File "image_infer.py", line 150, in <module>
    handler = Handler('./model/2d106det', 0, ctx_id=7, det_size=640)
  File "image_infer.py", line 89, in __init__
    self.detector.prepare(ctx_id=ctx_id)
AttributeError: 'NoneType' object has no attribute 'prepare'
```
hi! @faisalshahbaz 

i got same issue

did you solved it?

**Comment by devinhee** [comment]
> I had the same problem - `get_model` doesn't seem to be throwing the error when downloading the model.
> 
> I fixed it by manually downloading the models and copying them over to the specified folder as detailed [here](https://github.com/deepinsight/insightface/tree/master/python-package).

I got the same error, and I downloaded the model file and put them into the folder, but it did't fix my problem. Anyway thanks.

**Comment by devinhee** [comment]
> I had the same problem - `get_model` doesn't seem to be throwing the error when downloading the model.
> 
> I fixed it by manually downloading the models and copying them over to the specified folder as detailed [here](https://github.com/deepinsight/insightface/tree/master/python-package).

I got the same error, and I downloaded the model files and put them into the folder, but it did't fix my problem. Anyway thanks.

**Comment by devinhee** [comment]
> I had the same problem - `get_model` doesn't seem to be throwing the error when downloading the model.
> 
> I fixed it by manually downloading the models and copying them over to the specified folder as detailed [here](https://github.com/deepinsight/insightface/tree/master/python-package).

I got the same error, and I downloaded the model files and put them into the folder, but it did't fix my problem. Anyway thanks.

**Comment by gangeqian** [comment]
download our antelope model release by command:
insightface-cli model.download antelope
but not include retinaface_r50_v1.onnx 
I could get the mxnet model of retinaface_r50_v1-0000.params and retinaface_r50_v1-symbol.json, but mxnet2onnx get error.
where can I get the onnx models？

**Comment by WangYaoNUIG** [comment]
download the models put it into ~/.insightface/model then degrade insightface==0.1.5

**Comment by kiashann** [comment]
Hi everyone. How did you use face recognition models for comparing the faces of two people after this code?
What is the nms argument?

import insightface
model = insightface.model_zoo.get_model('retinaface_r50_v1')
model.prepare(ctx_id=-1, nms=0.4)

**Comment by SanjithKumar2** [comment]
it's been 4 years since this issue was raised and still this issue is there...
