### ISSUE TITLE
scrfd how to convert to onnx?

### ISSUE THREAD

**Issue by fisakhan** [deepinsight/insightface#1573]
While using scrfd2onnx.py, what should be the values of build_model_from_cfg, generate_inputs_and_wrap_model, and preprocess_example_input in `from mmdet.core import (build_model_from_cfg, generate_inputs_and_wrap_model, preprocess_example_input)`

**Comment by nttstar** [comment]
Please follow the example from our readme. Default settings should work.

**Comment by fisakhan** [comment]
I receive the following error

`ImportError: cannot import name 'build_model_from_cfg'`

Even though I can run the following example from mmdetection successfully

```
from mmdet.apis import init_detector, inference_detector, show_result_pyplot

config_file = 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
checkpoint_file = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
device = 'cuda:0'
model = init_detector(config_file, checkpoint_file, device=device)
device = 'cuda:0'
model = init_detector(config_file, checkpoint_file, device=device)
img = 'demo/demo.jpg'
result = inference_detector(model, img)
show_result_pyplot(model, img, result, score_thr=0.3)
```

**Comment by Sarthak-07** [comment]
I am having the same issue, can someone help me to figure this out?

**Comment by schliffen** [comment]
Could anyone could convert scrfd model to onnx. examples are not working:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SCRFD is not in the models registry'

**Comment by fisakhan** [comment]
@schliffen please run https://github.com/deepinsight/insightface/blob/master/detection/scrfd/tools/scrfd2onnx.py to generate onnx model

**Comment by chenscottus** [comment]
We are using  https://github.com/deepinsight/insightface/blob/master/detection/scrfd/tools/scrfd2onnx.py and get the error!

**Comment by chenscottus** [comment]
Change
from mmdet.core import (build_model_from_cfg, generate_inputs_and_wrap_model, preprocess_example_input)
==>>>>>
from mmdet.core.export import build_model_from_cfg, preprocess_example_input, generate_inputs_and_wrap_model

**Comment by rahulsharma11** [comment]
Hi, @chenscottus ,
Did above suggestion worked?

I did the same but still same error of KeyError: 'SCRFD is not in the models registry'

**Comment by lprfacial247** [comment]
I used "scrfd_2.5g_bnkps.py" as config file when converted the pth to onnx of 'scrfd_2.5g.pth'.
Of course, the onnx file is generated. but when check the onnx file, the output is empty.
what is issue?

**Comment by lprfacial247** [comment]
[scrfd_2.5g_bnkps.py](https://github.com/deepinsight/insightface/blob/master/detection/scrfd/configs/scrfd/scrfd_2.5g_bnkps.py)
and [scrfd_2.5g.py](https://github.com/deepinsight/insightface/blob/master/detection/scrfd/configs/scrfd/scrfd_2.5g.py) are same.
Only difference is "norm_cfg=dict(type='BN', requires_grad=True)" and "dict(type='GN', num_groups=16, requires_grad=True)".
But, after converted pth into onnx with 'bnkps' config file, that onnx does not work.
who can help me?

**Comment by ZubairKhan001** [comment]
@fisakhan try input_size=(256,256)

**Comment by quanqigu** [comment]
new issue: ModuleNotFoundError: No module named 'mmdet.core'

**Comment by nobody-cheng** [comment]
> new issue: ModuleNotFoundError: No module named 'mmdet.core'

![image](https://github.com/deepinsight/insightface/assets/34908468/e5b5f473-0815-4c73-b434-bbce6ce9cb23)

**Comment by thadanguyen** [comment]
Is this problem solved? I still cannot convert the pretrained scrfd_2.5 to onnx. It's still the error KeyError: 'SCRFD is not in the models registry'

**Comment by alexemme** [comment]
> Is this problem solved? I still cannot convert the pretrained scrfd_2.5 to onnx. It's still the error KeyError: 'SCRFD is not in the models registry'

You need to run /insightface/detection/scrfd/setup.py, but make sure that mmdet is NOT installed yet. The script will install it and automatically set its location to /insightface/detection/scrfd/mmdet, which contains the SCRFD model script file.

**Comment by chenjoya** [comment]
Find the correct pytorch version is crucial, otherwise you may face various compile problems.

Just succeed after many tries. A short summary for key packages:

```
python 3.9
Cython                 0.29.33
torch                  1.10.0 (cu113)
torchaudio             0.10.0
mmcv-full              1.3.3
```
