### ISSUE TITLE
[Alightment/coordinateReg] AttributeError: 'NoneType' object has no attribute 'prepare'

### ISSUE THREAD

**Issue by nhatduy19599** [deepinsight/insightface#1604]
**I have a problem running the file 'image_infer.py'**
------
Error: 
PS E:\DataTraining\insightface-master\insightface-master> & "C:/Program Files/Python36/python.exe" e:/DataTraining/insightface-master/insightface-master/alignment/coordinateReg/image_infer.py
loading ./model/2d106det 0
Traceback (most recent call last):
  File "e:/DataTraining/insightface-master/insightface-master/alignment/coordinateReg/image_infer.py", line 149, in <module>
    handler = Handler('./model/2d106det', 0, ctx_id=7, det_size=640)
  File "e:/DataTraining/insightface-master/insightface-master/alignment/coordinateReg/image_infer.py", line 88, in __init__ 
    self.detector.prepare(ctx_id=ctx_id)
AttributeError: 'NoneType' object has no attribute 'prepare'
---------------------
I have downloaded the model and put it in the correct link , What is the problem I am facing and what do I need to do to fix it.
thanks.

**Comment by cia1099** [comment]
I have the same problem too

**Comment by WangYaoNUIG** [comment]
I have the same problem too

**Comment by nadaboulares** [comment]
I need a guide to make recognition work any help plz
