### ISSUE TITLE
insightface.__version__>='0.4' : install failed

### ISSUE THREAD

**Issue by eeric** [deepinsight/insightface#1655]
https://github.com/deepinsight/insightface/blob/master/examples/person_detection/scrfd_person.py

**Comment by nttstar** [comment]
any detail?

**Comment by eeric** [comment]
pip install -U insightface==0.4
install failed

**Comment by nttstar** [comment]
I know you failed, but any detailed message?

**Comment by eeric** [comment]
Collecting insightface==0.4
  Using cached insightface-0.4.tar.gz (438 kB)
    ERROR: Command errored out with exit status 1:
     command: /2021/test_onnx/pytorch-1.8.1/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kw_cwfxm/insightface_6e86f31454974967a9dee85317259fed/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kw_cwfxm/insightface_6e86f31454974967a9dee85317259fed/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-q9bu2jfk
         cwd: /tmp/pip-install-kw_cwfxm/insightface_6e86f31454974967a9dee85317259fed/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kw_cwfxm/insightface_6e86f31454974967a9dee85317259fed/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0c/2f/5ae98ba12b500e6d878fd0c5c029741fca24e09fbd4bfa2800e6d9338e91/insightface-0.4.tar.gz#sha256=3463b9824688e4f5e88a6547c6528d7c878196713bebc64355c8a256fd4204c2 (from https://pypi.org/simple/insightface/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement insightface==0.4 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4)
ERROR: No matching distribution found for insightface==0.4

**Comment by nttstar** [comment]
pip install cython

**Comment by eeric** [comment]
according to error message
installing Cython and so on.
now successfully.

**Comment by zdxpan** [comment]
```
ipython 
import numpy 
numpy.get_include()

sudo cp -r /Users/xxxxxxxxxx/anaconda3/envs/sd/lib/python3.10/site-packages/numpy/core/include/numpy 
/usr/local/include

```
it perfectly solve this problem
