### ISSUE TITLE
tools的情况

### ISSUE THREAD

**Issue by iiphenoix** [deepinsight/insightface#1674]
我有自己的原始数据集，是bmp格式，试图转成bin格式，报错。似乎tools里py代码需要修改才能正常运行。

**Comment by iiphenoix** [comment]
Traceback (most recent call last):
  File "tools/convert_image_bin.py", line 81, in <module>
    main(args)
  File "tools/convert_image_bin.py", line 55, in main
    img_list = get_file_list(args.image_path)
  File "tools/convert_image_bin.py", line 25, in get_file_list
    if single_file.split('.')[-1] in img_end:
NameError: name 'img_end' is not defined

**Comment by nttstar** [comment]
@littletomatodonkey

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，我们在这个pr中修复了哈，另外也添加了对于原始图像文件的读取方式，将`is_bin`参数修改为False即可
#1675 ，文档中也有关于该参数的说明~

**Comment by iiphenoix** [comment]
> 你好，感谢反馈，我们在这个pr中修复了哈，另外也添加了对于原始图像文件的读取方式，将`is_bin`参数修改为False即可
> #1675 ，文档中也有关于该参数的说明~

太感谢了
