### ISSUE TITLE
Error When Training Retinaface with mobilenet.25

### ISSUE THREAD

**Issue by jacqueline-weng** [deepinsight/insightface#1702]
I got this error while training retinaface using mobilenet.25 as backbone.

> Traceback (most recent call last):
  File "train.py", line 503, in <module>
    main()
  File "train.py", line 499, in main
    lr_step=args.lr_step)
  File "train.py", line 391, in train_net
    num_epoch=end_epoch)
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/base_module.py", line 498, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 280, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 383, in bind_exec
    self._collect_arrays()
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 312, in _collect_arrays
    for name, _ in self.data_shapes]
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 312, in <listcomp>
    for name, _ in self.data_shapes]
  File "/usr/local/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 311, in <listcomp>
    self.data_arrays = [[(self.slices[i], e.arg_dict[name]) for i, e in enumerate(self.execs)]
  File "/usr/local/lib/python3.6/site-packages/mxnet/executor.py", line 277, in arg_dict
    self._symbol.list_arguments(), self.arg_arrays)
  File "/usr/local/lib/python3.6/site-packages/mxnet/executor.py", line 95, in _get_dict
    raise ValueError('Duplicate names detected, %s' % str(names))
It warns me that the variable name 'face_rpn_landmark_pred_stride32_weight' is used more than once. What adjustments should I make to solve this problem?

**Comment by nttstar** [comment]
You should use imagenet pre-trained model
