### ISSUE TITLE
How to load pretrained model to test?

### ISSUE THREAD

**Issue by DawnHH** [deepinsight/insightface#173]
百度网盘里给的模型和verification代码里用的名字似乎不同，没有办法用逗号分隔，net是空的。
The pretrained model “model-r50-am-lfw” can't split by "," the array net is empty.

**Comment by nttstar** [comment]
用epoch=0加载. 比如 "model-r50-am-lfw/model,0"

**Comment by cici-tan** [comment]
用百度网盘的pre_trained_model跑test.py得到了这个错误：
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    model = face_embedding.FaceModel(args)
  File "/Users/aei/insightface/deploy/face_embedding.py", line 52, in __init__
    model.bind(data_shapes=[('data', (1, 3, image_size[0], image_size[1]))])
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 264, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 360, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 638, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 1518, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)

**Comment by DawnHH** [comment]
没有遇到这个问题，我用的是src/eval/verification.py 测试的，确实是99.80+，不过你的问题看起来是GPU调用的问题，指定另一块卡跑跑看？

**Comment by cici-tan** [comment]
but an error came up when I trying verification:

Traceback (most recent call last):
  File "verification.py", line 518, in <module>
    prop = face_image.load_property(args.data_dir)
  File "../common/face_image.py", line 10, in load_property
    for line in open(os.path.join(data_dir, 'property')):
IOError: [Errno 2] No such file or directory: '../datasets/faces_ms1m_112x112/property'

Seem like something called property missed, did you have this problem?

**Comment by xisi789** [comment]
安装gpu下的mxnet, 例如mxnet-cu8.0
