### ISSUE TITLE
scrfd TypeError: 'DataContainer' object does not support indexing

### ISSUE THREAD

**Issue by sunzhongwu** [deepinsight/insightface#1733]
scrfd训练过程中在测试验证集会报下面这个错：
img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])
TypeError: 'DataContainer' object does not support indexing

**Comment by nttstar** [comment]
Can you list the package version?

**Comment by sunzhongwu** [comment]
坏境原因，那我大概知道是哪里的问题了，谢谢回复

**Comment by sunzhongwu** [comment]
> Can you list the package version?
> pip list | grep mmdet
> pip list | grep mmcv

又遇到个在转onnx的时候命令如下：
         python tools/scrfd2onnx.py  ./configs/scrfd/scrfd_500m_bnkps.py  ./work_dirs/scrfd_500m_bnkps/epoch_*.pth --shape -1 -1  --input-img pre_model/1.jpg
 报错：
Traceback (most recent call last):
  File "tools/scrfd2onnx.py", line 178, in <module>
    test_img=args.test_img)
  File "tools/scrfd2onnx.py", line 62, in pytorch2onnx
    model = onnx.load(ori_output_file)
AttributeError: module 'onnx' has no attribute 'load'
请教一下这个是怎么回事呢？

**Comment by nttstar** [comment]
没碰到过. onnx什么版本？

**Comment by sunzhongwu** [comment]
> 没碰到过. onnx什么版本？

我的问题，没有安装onnx ，pip安装后就转换成功率，谢谢

**Comment by sunzhongwu** [comment]
还有个问题，训练怎么修改batchsize?在config中没有找到这个参数

**Comment by Kayterancer** [comment]
> 环境原因，那我大概知道是哪里的问题了，谢谢回复

请问这个问题解决了嘛？具体是什么环境问题

**Comment by Suvi-dha** [comment]
Hi, there is error in the code:

Use`: img_meta.data[0][img_id]['batch_input_shape'] = tuple(img.size()[-2:])`

instead of: `img_meta[img_id]['batch_input_shape'] = tuple(img.size()[-2:])`

make these changes everywhere wherever img_meta is subscripted. 

Hope this helps.
