### ISSUE TITLE
arcface_torch/eval/verification.py

### ISSUE THREAD

**Issue by PPPPPPPeng** [deepinsight/insightface#1760]
```
def test(data_set, backbone, batch_size, nfolds=10):
    print('testing verification..')
    data_list = data_set[0]
    issame_list = data_set[1]
    embeddings_list = []
    time_consumed = 0.0
    for i in range(len(data_list)):
        data = data_list[i]
        embeddings = None
        ba = 0
        while ba < data.shape[0]:
            bb = min(ba + batch_size, data.shape[0])
            count = bb - ba
            _data = data[bb - batch_size: bb]
            time0 = datetime.datetime.now()
            img = ((_data / 255) - 0.5) / 0.5
            **net_out: torch.Tensor = backbone(img)**
            _embeddings = net_out.detach().cpu().numpy()
            time_now = datetime.datetime.now()
            diff = time_now - time0
            time_consumed += diff.total_seconds()
            if embeddings is None:
                embeddings = np.zeros((data.shape[0], _embeddings.shape[1]))
            embeddings[ba:bb, :] = _embeddings[(batch_size - count):, :]
            ba = bb
        embeddings_list.append(embeddings)
 I got  such error:
Traceback (most recent call last):
  File "/home/yl/PycharmProjects/sumail/insightface/recognition/arcface_torch/eval/verification.py", line 400, in <module>
    acc1, std1, acc2, std2, xnorm, embeddings_list = tes( ver_list[i], model, args.batch_size, args.nfolds)
  File "/home/yl/anaconda3/envs/insightface/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/yl/PycharmProjects/sumail/insightface/recognition/arcface_torch/eval/verification.py", line 244, in tes
    net_out: torch.Tensor = backbone(img)
TypeError: 'Module' object is not callable

**Comment by epns** [comment]
what's data_set, is it test dataset?
