### ISSUE TITLE
insightface_paddle cannot resume training while loading checkpoint...

### ISSUE THREAD

**Issue by Nise-2-meet-U** [deepinsight/insightface#1808]
Training: 2021-11-02 19:58:58,427 - Load checkpoint from '/home/bbs/Datasets/kjj/insightface/recognition/arcface_paddle/MS1M_v2_arcface_MobileFaceNet_128_0.1/MobileFaceNet_128/120'.
Traceback (most recent call last):
  File "tools/train.py", line 35, in <module>
    train(args)
  File "/home/bbs/Datasets/kjj/insightface/recognition/arcface_paddle/dynamic/train.py", line 168, in train
    backbone, classifier, optimizer, for_train=True)
  File "/home/bbs/Datasets/kjj/insightface/recognition/arcface_paddle/dynamic/utils/io.py", line 229, in load
    classifier.state_dict(), dist_param_state_dict)
  File "/home/bbs/Datasets/kjj/insightface/recognition/arcface_paddle/dynamic/utils/io.py", line 220, in map_actual_param_name
    state_dict[name] = load_state_dict[param.name]
KeyError: 'dist@fc@rank@00000'

**Comment by GuoxiaWang** [comment]
@Nise-2-meet-U  Fixed
