### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by iumyx2612** [deepinsight/insightface#1835]
I try to do inference on your pretrained model following: https://github.com/deepinsight/insightface/blob/master/examples/demo_analysis.py
Here's my code:
```
import insightface
from cv2 import cv2

app = insightface.app.FaceAnalysis()
app.prepare(0, det_size=640)
image = cv2.imread("my-picture.jpg")
faces = app.get(image)
assert len(faces)==6
rimg = app.draw_on(image, faces)
cv2.imwrite("output.jpg", rimg)
```

Error: 
```
Traceback (most recent call last):
  File "E:\Work work\Python\Work\atin\FaceRecog\main.py", line 7, in <module>
    faces = app.get(image)
  File "E:\Anaconda\envs\insightface\lib\site-packages\insightface\app\face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
  File "E:\Anaconda\envs\insightface\lib\site-packages\insightface\model_zoo\retinaface.py", line 212, in detect
    model_ratio = float(input_size[1]) / input_size[0]
TypeError: 'int' object is not subscriptable
find model: .insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: 640
```

**Comment by nttstar** [comment]
set det_size = (640, 640)

**Comment by iumyx2612** [comment]
> set det_size = (640, 640)

Thank you
