### ISSUE TITLE
AssertionError: model_file should exist

### ISSUE THREAD

**Issue by Beartx** [deepinsight/insightface#1912]
i have downloaded antelope which is the pretrain model right?
i get this issue whenever trying to call the detection or recognition model in the quick example

Traceback (most recent call last):
  File "D:/insightface/python-package/main.py", line 8, in <module>
    detector = insightface.model_zoo.get_model('glintr100.onnx')
  File "D:\insightface\python-package\insightface\model_zoo\model_zoo.py", line 80, in get_model
    assert osp.exists(model_file), 'model_file should exist'
AssertionError: model_file should exist 

so am wondering what is the correct way of setting this model?

**Comment by Beartx** [comment]
![main](https://user-images.githubusercontent.com/61374854/154212418-09b1aed5-a068-49f2-bcb4-ac86823bcfb7.PNG)

am trying this code so after i try the detector with the path it just redownload the antelope which is already exist in my file and i don't see the different, as the code by default detect the faces so i commented and tried to call the recognition model with the same path but i get again same issue 
assert osp.exists(model_file), 'model_file should exist'
AssertionError: model_file should exist

**Comment by Beartx** [comment]
any idea?

**Comment by EylonSho** [comment]
Try to use the full absolute path.
`/home/user/.../glintr100.onnx` instead of `~/.insightface/.../glintr100.onnx`
