### ISSUE TITLE
A problem about training arcface_torch with webface42m

### ISSUE THREAD

**Issue by sattychen** [deepinsight/insightface#2004]
when I training arcface_torch with webface42m dataset，after several block is traind，a mxnet error is raised，such as :
 raining: 2022-05-12 19:24:28,156-Speed 1141.43 samples/sec   Loss 42.5226   LearningRate 0.0997   Epoch: 0   Global Step: 4500   Fp16 Grad Scale: 131072   Required: 283 hours
Training: 2022-05-12 19:24:30,424-Speed 1128.66 samples/sec   Loss 42.5116   LearningRate 0.0997   Epoch: 0   Global Step: 4510   Fp16 Grad Scale: 131072   Required: 283 hours
Training: 2022-05-12 19:24:32,675-Speed 1137.82 samples/sec   Loss 42.4941   LearningRate 0.0997   Epoch: 0   Global Step: 4520   Fp16 Grad Scale: 131072   Required: 282 hours
Training: 2022-05-12 19:24:34,936-Speed 1132.51 samples/sec   Loss 42.5565   LearningRate 0.0997   Epoch: 0   Global Step: 4530   Fp16 Grad Scale: 131072   Required: 282 hours
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/cgb/insightface-master/recognition/arcface_torch/dataset.py", line 53, in run
    for item in self.generator:
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
mxnet.base.MXNetError: Caught MXNetError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cgb/insightface-master/recognition/arcface_torch/dataset.py", line 130, in __getitem__
    sample = mx.image.imdecode(img).asnumpy()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mxnet/image/image.py", line 211, in imdecode
    return cvimdecode(buf, *args, **kwargs)
  File "<string>", line 38, in _cvimdecode
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mxnet/_ctypes/ndarray.py", line 91, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/io/image_io.cc", line 189
MXNetError: Check failed: len > 0: Input cannot be an empty buffer

If i train arcface_torch with wf12m dataset, it's  no problem .
 
I don't change any training code . Only modify config file, the config file  such as ：

from easydict import EasyDict as edict

# make training faster
# our RAM is 256G
# mount -t tmpfs -o size=140G  tmpfs /train_tmp

config = edict()
config.margin_list = (1.0, 0.0, 0.4)
config.network = "r100"
config.resume = False
config.output = None
config.embedding_size = 512
config.sample_rate = 0.2
config.fp16 = True
config.momentum = 0.9
config.weight_decay = 5e-4
config.batch_size = 128
config.lr = 0.1
config.verbose = 2000
config.dali = False

config.rec = "/data2/dataset/webface42m"
config.num_classes = 2059906
config.num_image = 42474557
config.num_epoch = 20
config.warmup_epoch = 0
config.val_targets = ['lfw', 'cfp_fp', "agedb_30"]

dataset error or environment error?

**Comment by LB15642219539** [comment]
Hello: I also encountered this problem! Have you solved this problem? Can you share your solutions?

**Comment by mlourencoeb** [comment]
It seems to me a problem with your dataset. Did you built it? Did you check that the total number of classes and images in the config file match the ones in your dataset?
