### ISSUE TITLE
how to change cuda version?

### ISSUE THREAD

**Issue by LeeKyungwook** [deepinsight/insightface#201]
Traceback (most recent call last):
  File "verification.py", line 43, in <module>
    import mxnet as mx
  File "/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/usr/local/lib/python2.7/dist-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 111, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 103, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

This is my error. However, I install cuda 9.1 , not cuda 8.0. So how can I change cuda path or code in this git source?

**Comment by xmuszq** [comment]
@LeeKyungwook    how did you solve this issue?

**Comment by LeeKyungwook** [comment]
@xmuszq  I sovled it. Make sure your cuda path is right. 
Or you can try this command line.
`sudo sh -c "echo '/usr/local/cuda/lib64\n/usr/local/cuda/lib' >> /etc/ld.so.conf.d/nvidia.conf"
sudo ldconfig`

**Comment by xmuszq** [comment]
@LeeKyungwook  Thank you!
