### ISSUE TITLE
About deploy/test.py 

### ISSUE THREAD

**Issue by lovehuanhuan** [deepinsight/insightface#202]
I can't run this test ,got stuck .

root@tegra-ubuntu:/home/nvidia/zhuzhipeng/insightface/deploy# python test.py
loading ../models/model-r34-amf/model 0
[07:28:23] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.12.1. Attempting to upgrade...
[07:28:23] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[07:28:23] src/engine/engine.cc:55: MXNet start using engine: NaiveEngine
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model = face_embedding.FaceModel(args)
  File "/home/nvidia/zhuzhipeng/insightface/deploy/face_embedding.py", line 52, in __init__
    model.bind(data_shapes=[('data', (1, 3, image_size[0], image_size[1]))])
  File "/home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/python/mxnet/module/module.py", line 430, in bind
    state_names=self._state_names)
  File "/home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/python/mxnet/module/executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/python/mxnet/module/executor_group.py", line 361, in bind_exec
    shared_group))
  File "/home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/python/mxnet/module/executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/python/mxnet/symbol/symbol.py", line 1524, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
[07:28:27] /home/nvidia/zhuzhipeng/mxnetTX2/incubator-mxnet/3rdparty/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:110: Check failed: err == cudaSuccess (48 vs. 0) Name: MapPlanKernel ErrStr:no kernel image is available for execution on the device

**Comment by lovehuanhuan** [comment]
@nttstar

**Comment by KKKarunaZ** [comment]
请问这个最后怎么解决的啊
