### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (19200,) (12800,) 

### ISSUE THREAD

**Issue by axi986** [deepinsight/insightface#2042]
运行scrdf报错
Traceback (most recent call last):
  File "D:/yolo/insightface-master/detection/scrfd/tools/scrfd.py", line 318, in <module>
    bboxes, kpss = detector.detect(img, 0.5, input_size = (640, 640))
  File "D:/yolo/insightface-master/detection/scrfd/tools/scrfd.py", line 225, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, thresh)
  File "D:/yolo/insightface-master/detection/scrfd/tools/scrfd.py", line 195, in forward
    bboxes = distance2bbox(anchor_centers, bbox_preds)
  File "D:/yolo/insightface-master/detection/scrfd/tools/scrfd.py", line 38, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
ValueError: operands could not be broadcast together with shapes (19200,) (12800,)

**Comment by usmancheema89** [comment]
similar issue when using insightface at same point.

**Comment by Rakeshkumar-7** [comment]
I'm have the same issue with this line

**Comment by bighammer-link** [comment]
input resolution must be a multiple of 32
