### ISSUE TITLE
export from pytorch to onnx using `torch2onnx.py` is not working

### ISSUE THREAD

**Issue by internnos** [deepinsight/insightface#2065]
hi

i'm trying to export pytorch model to onnx using this [script](https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/torch2onnx.py) but it doesn't work

```
 python3 torch2onnx.py backbone.pth --network r100 --output model.onnx
```

the model i'm using is `MS1MV3/backbone.pth`

this is the error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: '2\nq\x03((X\x07'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/usr/lib/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "torch2onnx.py", line 53, in <module>
    convert_onnx(backbone_onnx, input_file, args.output, simplify=args.simplify)
  File "torch2onnx.py", line 14, in convert_onnx
    weight = torch.load(path_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: backbone.pth is a zip archive (did you mean to use torch.jit.load()?)
```

and this is my env using `FROM nvidia/cuda:11.4.0-devel-ubuntu18.04` as base image
```
asn1crypto==0.24.0
attrs==22.1.0
awscli==1.18.69
blessed==1.19.1
botocore==1.16.19
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.7
cryptography==2.1.4
cycler==0.11.0
decorator==4.4.2
distro==1.7.0
docutils==0.14
easydict==1.9
enforce==0.3.4
enlighten==1.10.2
flatbuffers==2.0
idna==2.6
imageio==2.15.0
importlib-metadata==4.8.3
iniconfig==1.1.1
jmespath==0.9.3
joblib==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.3.1
matplotlib==3.3.4
networkx==2.5.1
numpy==1.19.5
onnx==1.11.0
onnxruntime-gpu==1.10.0
opencv-python==4.1.0.25
packaging==21.3
Pillow==8.4.0
pluggy==1.0.0
prefixed==0.3.2
protobuf==3.19.4
py==1.11.0
pyasn1==0.4.2
pycrypto==2.6.1
PyGObject==3.26.1
pyparsing==3.0.9
pytest==7.0.1
python-dateutil==2.8.2
PyWavelets==1.1.1
pyxdg==0.25
PyYAML==6.0
requests==2.18.4
roman==2.0.0
rsa==3.4.2
s3transfer==0.3.3
scikit-build==0.11.1
scikit-image==0.15.0
scikit-learn==0.24.1
scipy==1.5.4
SecretStorage==2.3.1
six==1.11.0
terminaltables==3.1.0
threadpoolctl==3.1.0
tomli==1.2.3
torch==1.2.0
tqdm==4.32.1
typing_extensions==4.1.1
urllib3==1.22
wcwidth==0.2.5
wrapt==1.14.1
zipp==3.6.0
```

thank you

**Comment by nttstar** [comment]
It seems the PyTorch checkpoint file you are trying to load is not correct.

**Comment by internnos** [comment]
aah yeah its saving and loading from different version, it works when i use the same. closing this. thank you
