### ISSUE TITLE
fine_turn with TripletLoss got a bug.

### ISSUE THREAD

**Issue by Wisgon** [deepinsight/insightface#207]
Traceback (most recent call last):
  File "train_softmax.py", line 485, in <module>
    main()
  File "train_softmax.py", line 482, in main
    train_net(args)
  File "train_softmax.py", line 334, in train_net
    sym, arg_params, aux_params = get_symbol(args, arg_params, aux_params)
  File "train_softmax.py", line 268, in get_symbol
    softmax = mx.symbol.SoftmaxOutput(data=fc7, label = gt_label, name='softmax', normalization='valid')

I read the code in train_softmax.py, there is no "loss_type==12" !?

**Comment by Wisgon** [comment]
Ok, thanks for reply.
