### ISSUE TITLE
torchrun can't replace torch.distributed.launch

### ISSUE THREAD

**Issue by young-chao** [deepinsight/insightface#2163]
I want to use 
`torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=12581 train.py configs/myconfig.py` 
to run the [example](https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/train.py) rather than
 `python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=12581 train.py configs/myconfig.py`.

However, there are some errors:
```
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Training: 2022-11-08 09:01:32,354-rank_id: 0
2022-11-08 09:01:32.515047: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 216, in <module>
  File "train.py", line 216, in <module>
        main(parser.parse_args())main(parser.parse_args())

  File "train.py", line 61, in main
  File "train.py", line 61, in main
        train_loader = get_dataloader(train_loader = get_dataloader(

  File "/workspace/workfile/Projects/arcface/dataset.py", line 57, in get_dataloader
  File "/workspace/workfile/Projects/arcface/dataset.py", line 57, in get_dataloader
        train_sampler = DistributedSampler(train_sampler = DistributedSampler(

  File "/workspace/workfile/Projects/arcface/utils/utils_distributed_sampler.py", line 100, in __init__
  File "/workspace/workfile/Projects/arcface/utils/utils_distributed_sampler.py", line 100, in __init__
        self.seed = sync_random_seed(seed)self.seed = sync_random_seed(seed)

  File "/workspace/workfile/Projects/arcface/utils/utils_distributed_sampler.py", line 77, in sync_random_seed
  File "/workspace/workfile/Projects/arcface/utils/utils_distributed_sampler.py", line 77, in sync_random_seed
        dist.broadcast(random_num, src=0)dist.broadcast(random_num, src=0)

  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
        work = default_pg.broadcast([tensor], opts)work = default_pg.broadcast([tensor], opts)

RuntimeErrorRuntimeError: : NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, invalid usage, NCCL version 2.10.3
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 686359) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-08_09:01:40
  host      : 7fc50ceb0af6
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 686360)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-08_09:01:40
  host      : 7fc50ceb0af6
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 686359)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by anxiangsir** [comment]
Thank you, we will fixed it.

**Comment by anxiangsir** [comment]
We have updated `torch.distributed.launch` to `torchrun`.

**Comment by LocNgoXuan23** [comment]
Dear @anxiangsir i still got the bug like the author can you help me ?  @anxiangsir 

my env is: conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.6 -c pytorch -c conda-forge
Error:
![image](https://github.com/user-attachments/assets/2fb2f623-4874-48f4-a332-6d5b61b5cd9f)
