### ISSUE TITLE
Fine-tune Pytorch ArcFace pre-trained model on custom data

### ISSUE THREAD

**Issue by Nomiluks** [deepinsight/insightface#2215]
Hi guys,

I want to fine-tune the Arcface model on my custom dataset. I am facing some errors. The details are shared below:

**Arcface Pytorch Repo:** https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch
**Pre-trained Model (model to fine-tune):** [ms1mv3_arcface_r50_fp16](https://onedrive.live.com/?authkey=%21AFZjr283nwZHqbA&id=4A83B6B633B029CC%215583&cid=4A83B6B633B029CC) `file:` rank_0_softmax_weight.pt

**Model Config:**
I set the *` config.resume `* flag to true (to load the pre-trained model for training)
`config.resume = True`

**Command I used to train the model:**
`python -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="127.0.0.1" --master_port=12581 train.py configs/ms1mv3_r50`

When I run the above command I get an error:

```
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    main(parser.parse_args())
  File "train.py", line 176, in the main
    start_epoch = dict_checkpoint["epoch"]
IndexError: too many indices for the tensor of dimension 
```

Please guide me on how I can fine-tune the model using faceinsight.

**Comment by Nomiluks** [comment]
Found my answer here: https://github.com/deepinsight/insightface/issues/2210

**Comment by praneet195** [comment]
I get the following error when I try to load the same model file using the solution you found:

`  
File "train.py", line 125, in main
    for k, v in pretrained_dict.items():
AttributeError: 'Tensor' object has no attribute 'items'
`

Any idea why?

Thanks

**Comment by nqthai309** [comment]
> I get the following error when I try to load the same model file using the solution you found:
> 
> ` File "train.py", line 125, in main for k, v in pretrained_dict.items(): AttributeError: 'Tensor' object has no attribute 'items'`
> 
> Any idea why?
> 
> Thanks

the same

**Comment by MetaInsight7** [comment]
I had the same problem, is there a solution now？
