### ISSUE TITLE
SCRFD ONNX model cant be inferenced with 1100x1650 as in Pytorch inference? it only works with Square resolutions.

### ISSUE THREAD

**Issue by Nuwan1654** [deepinsight/insightface#2232]
I am getting the following error

Traceback (most recent call last):
  File "face_annotator.py", line 319, in <module>
    bboxes, kpss = detector.detect(img, args.thresh, input_size = (int(args.imgz[0]), int(args.imgz[1])))
  File "face_annotator.py", line 229, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, thresh)
  File "face_annotator.py", line 199, in forward
    bboxes = distance2bbox(anchor_centers, bbox_preds)
  File "face_annotator.py", line 46, in distance2bbox
    x1 = points[:, 0] - distance[:, 0]
ValueError: operands could not be broadcast together with shapes (56444,) (56856,)

**Comment by Nuwan1654** [comment]
Got it. for onnx,  resolution must be a multiple of 32
