### ISSUE TITLE
Cast error with PyTorch 1.12 in label

### ISSUE THREAD

**Issue by ocanevet** [deepinsight/insightface#2241]
Hello,

Thanks for making your code available.

Since the update to PyTorch 1.12, I have an error due to a float label value not castable to a long one:

File "[...]/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
  data = [self.dataset[idx] for idx in possibly_batched_index]
File "[...]/insightface/recognition/arcface_torch/dataset.py", line 166, in __getitem__
  label = torch.tensor(label, dtype=torch.long)
TypeError: 'float' object cannot be interpreted as an integer

https://github.com/deepinsight/insightface/blob/f488f4de5622c4001b52f98845f6ba422c34ec77/recognition/arcface_torch/dataset.py#L165

I tried to regenerate the `.rec` file with labels of type long (by removing `.000000` in the `train.lst`) but that does not work.

However, updating the line with `label = torch.tensor(int(label), dtype=torch.long)` solves the issue.

Does anyone get the same problem?

Thanks.

**Comment by anxiangsir** [comment]
Hi, when I was using torch 1.12 and the official `ms1m-retinaface-t1`, I did not encounter this issue.

```shell
In [1]: import torch

In [2]: torch.__version__
Out[2]: '1.12.0+cu113'
```

Could you provide more information about your torch versions and rec so that I can try to reproduce the error? Thanks.

**Comment by ocanevet** [comment]
Thanks for you feedback. I installed PyTorch with conda. When I compare versions 1.11 and 1.12, I get the following:

```
>>> torch.__version__
'1.11.0'
>>> torch.tensor(1.123, dtype=torch.long)
<stdin>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
tensor(1)

>>> torch.__version__
'1.12.0'
>>> torch.tensor(1.123, dtype=torch.long)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer


>>> torch.__version__
'1.12.1'
>>> torch.tensor(1.123, dtype=torch.long)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```
I generated the `.rec` file with the provided commands:
```
python -m mxnet.tools.im2rec --list --recursive train /data/webface
python -m mxnet.tools.im2rec --num-thread 8 --quality 100 train /data/webface
```
The `.yaml` file I used for the installation is:
```
name: insight
dependencies:
  - python=3.10
  - pytorch::pytorch=1.12
  - pytorch::torchvision
  - pytorch::torchaudio
  - cudatoolkit=11.3
  - numpy
  - scikit-learn
  - scikit-learn-intelex
  - pip
  - pip:
    - tensorboard
    - easydict
    - mxnet
    - onnx
    - opencv-python
```
and installation with
```
conda env create -f insight.yaml
```
I hope this helps.
