### ISSUE TITLE
onnx_helper error

### ISSUE THREAD

**Issue by SuyueLiu** [deepinsight/insightface#2300]
when I run onnx_helper to check the trained onnx model(generate by the default code), I got an error:
![image](https://github.com/deepinsight/insightface/assets/49122192/d6e39ac4-c4e8-4278-912d-5c5caf9f6250)

Traceback (most recent call last):
  File "onnx_helper.py", line 251, in <module>
    err = handler.check(args.track)
  File "onnx_helper.py", line 166, in check
    batch_result = self.check_batch(test_img)
  File "onnx_helper.py", line 200, in check_batch
    net_out = self.session.run(self.output_names, {self.input_name: blob})[0]

onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gemm node. Name:'Gemm_185' Status Message: GEMM: Dimension mismatch, W: {512,512} K: 16384 N:512

input: [None, 3, 112, 112]
The onnx_helper blob shape: [32, 3, 112, 112]

Does any one know how to solve this problem?

**Comment by SuyueLiu** [comment]
> Have you converted the ONNX model to a format that supports batch inference? (where input_shape[0] is in string type)

yes I did
![image](https://github.com/deepinsight/insightface/assets/49122192/2f4e2a19-8232-4402-a7fa-d42e39097867)

**Comment by hyperf0cus** [comment]
Any updates???

**Comment by imCaoQuoc** [comment]
Try change the code in torch2onnx.py, line 17 to 
torch.onnx.export(net, img, output, input_names=["data"], output_names=["fc1"], keep_initializers_as_inputs=False, verbose=False, opset_version=opset, dynamic_axes={"data": {0: "batch_size"}, "fc1": {0: "batch_size"}})

This worked for me.
