### ISSUE TITLE
cudaErrorCudartUnloading CUDA: unknown error

### ISSUE THREAD

**Issue by IdeoG** [deepinsight/insightface#234]
Hello @nttstar

I didn't found exact problem in current issues. Could you help me solve the issue please?
My GPU is 950M with 4GB dedicated memory. I use cuda-9.1 with mxnet-cu91 module.
``` bash 
$ CUDA_VISIBLE_DEVICES='0' python2 -u train_softmax.py --network r100 --loss-type 4 --margin-m 0.5 --data-dir ../datasets/faces_emore --prefix ../model 
gpu num: 1
num_layers 100
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=128, beta=1000.0, beta_freeze=0, beta_min=5.0, bn_mom=0.9, ckpt=1, ctx_num=1, cutoff=0, data_dir='../datasets/faces_emore', easy_margin=0, emb_size=512, end_epoch=100000, fc7_wd_mult=1.0, gamma=0.12, image_channel=3, image_h=112, image_w=112, loss_type=4, lr=0.1, lr_steps='', margin=4, margin_a=1.0, margin_b=0.0, margin_m=0.5, margin_s=64.0, max_steps=0, mom=0.9, network='r100', num_classes=85742, num_layers=100, per_batch_size=128, power=1.0, prefix='../model', pretrained='', rand_mirror=1, rescale_threshold=0, scale=0.9993, target='lfw,cfp_fp,agedb_30', use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
init resnet 100
0 1 E 3 prelu
INFO:root:loading recordio ../datasets/faces_emore/train.rec...
header0 label [5822654. 5908396.]
id2range 85742
5822653
rand_mirror 1
[16:41:23] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000L, 3L, 112L, 112L)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000L, 3L, 112L, 112L)
ver agedb_30
lr_steps [400000, 560000, 640000]
Traceback (most recent call last):
  File "train_softmax.py", line 485, in <module>
    main()
  File "train_softmax.py", line 482, in main
    train_net(args)
  File "train_softmax.py", line 476, in train_net
    epoch_end_callback = epoch_cb )
  File "/usr/lib/python2.7/site-packages/mxnet/module/base_module.py", line 484, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/lib/python2.7/site-packages/mxnet/module/module.py", line 430, in bind
    state_names=self._state_names)
  File "/usr/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 361, in bind_exec
    shared_group))
  File "/usr/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 1519, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 3, 112, 112)
softmax_label: (128,)
[16:41:41] src/storage/storage.cc:119: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error

Stack trace returned 10 entries:
[bt] (0) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x31a18a) [0x7f32ed68618a]
[bt] (1) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x31a7b1) [0x7f32ed6867b1]
[bt] (2) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x29e36e3) [0x7f32efd4f6e3]
[bt] (3) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x29e65df) [0x7f32efd525df]
[bt] (4) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x29e7a9f) [0x7f32efd53a9f]
[bt] (5) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24a13c3) [0x7f32ef80d3c3]
[bt] (6) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24a153d) [0x7f32ef80d53d]
[bt] (7) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24adfef) [0x7f32ef819fef]
[bt] (8) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24b4bd0) [0x7f32ef820bd0]
[bt] (9) /usr/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x24c1232) [0x7f32ef82d232]
```

Thanks a lot.

**Comment by IdeoG** [comment]
I was able to train network with almost same command (batch size = 16) before. 
I tried to do it now with same batch size, but had no luck. 
I don't think, that is out of memory, because my gpu not loaded at that moment.

**Comment by polarisZhao** [comment]
I have same error, how to solve this problem?

**Comment by IdeoG** [comment]
I have no idea. Just forget it.

**Comment by abyellow** [comment]
me too. how to solve it?

**Comment by abyellow** [comment]
I'm trying this now: https://github.com/apache/incubator-mxnet/issues/9031

**Comment by JeasonUESTC** [comment]
Hi，Have you solve this problem? I have the same error.

**Comment by rocinant** [comment]
I have exactly same error, anyone knows how to solve this problem?
