### ISSUE TITLE
I meet some error in testing verification

### ISSUE THREAD

**Issue by divided7** [deepinsight/insightface#2438]
```Training: 2023-09-26 16:40:24,409-Speed 693.81 samples/sec   Loss 42.1715   LearningRate 0.020000   Epoch: 0   Global Step: 20   Fp16 Grad Scale: 8192   Required: 86 hours
testing verification..
(12000, 512)
infer time 21.899862999999975
Traceback (most recent call last):
  File "train_v2.py", line 291, in <module>
    main(parser.parse_args())
  File "train_v2.py", line 248, in main
    callback_verification(global_step, backbone)
  File "/app/user1/arcface/utils/utils_callbacks.py", line 64, in __call__
    self.ver_test(backbone, num_update)
  File "/app/user1/arcface/utils/utils_callbacks.py", line 31, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(
  File "/app/user1/miniconda3/envs/pytorchv1/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/app/user1/arcface/eval/verification.py", line 272, in test
    _, _, accuracy, val, val_std, far = evaluate(embeddings, issame_list, nrof_folds=nfolds)
  File "/app/user1/arcface/eval/verification.py", line 191, in evaluate
    val, val_std, far = calculate_val(thresholds,
  File "/app/user1/arcface/eval/verification.py", line 151, in calculate_val
    f = interpolate.interp1d(far_train, thresholds, kind='slinear')
  File "/app/user1/miniconda3/envs/pytorchv1/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 616, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/app/user1/miniconda3/envs/pytorchv1/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1293, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates

**Comment by AAAXiaoShen** [comment]
How was it solved?
