### ISSUE TITLE
can not install Insightface

### ISSUE THREAD

**Issue by ShyrmanGPA** [deepinsight/insightface#2451]
Hi tryed now few tings to get it installed but get always the same error message :/

PS C:\Users\User\Desktop\SD> pip install insightface==0.7.3
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from insightface==0.7.3)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/d7/1cc7a11118408ad21a5379ff2a4e0b0e27504c68ef6e808ebaa90ee95902/numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting onnx (from insightface==0.7.3)
  Using cached onnx-1.14.1.tar.gz (11.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-myutqko2\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-myutqko2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-myutqko2\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-myutqko2\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 85, in <module>
      AssertionError: Could not find cmake executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\User\Desktop\SD>

**Comment by Ankit325** [comment]
Do you have cmake installed?
Before installing insightface try to install
gcc, g++, cmake and after that do,
'pip install onnx onnxruntime'
And then do 
'pip install insightface'

**Comment by Justin27482** [comment]
Also, for clarity since I spun my wheels for an hour on this also.  By install cmake it means go to cmake.org, find the installer fitting your operating system and install it choosing to add CMAKE to your path.  

Running 'pip install cmake' (which does execute and reports success) does NOT actually install the CMAKE binary and put it in the path.

**Comment by Thehunk1206** [comment]
Simply install python-dev
`sudo apt install python-dev`

**Comment by sitzbrau** [comment]
on Ubuntu with Python 3.10 i've solved with this Wheel
[](https://www.wheelodex.org/projects/insightface/wheels/insightface-0.2.1-py2.py3-none-any.whl/)
and in the same folder 
`pip install insightface-0.2.1-py2.py3-none-any.whl`
