### ISSUE TITLE
how many iterations needed to generate a model?

### ISSUE THREAD

**Issue by anguoyang** [deepinsight/insightface#248]
I have trained the model according to  the tutorial, now it is the epoch 9/batch 18000, it seems that no temp model generated

**Comment by maryhh** [comment]
python train_softmax.py --ckpt 2 to save

**Comment by anguoyang** [comment]
Traceback (most recent call last):
  File "train_softmax.py", line 485, in <module>
    main()
  File "train_softmax.py", line 482, in main
    train_net(args)
  File "train_softmax.py", line 304, in train_net
    prop = face_image.load_property(data_dir)
  File "/media/anguoyang/SSD/DeepLearning/Face/insightface/src/common/face_image.py", line 10, in load_property
    for line in open(os.path.join(data_dir, 'property')):
IOError: [Errno 2] No such file or directory: 'property'

**Comment by anguoyang** [comment]
@nttstar  is there any documents on those command line?

**Comment by nttstar** [comment]
check the files in our training dataset.
