### ISSUE TITLE
antelopev2 is not available for download

### ISSUE THREAD

**Issue by kovalexal** [deepinsight/insightface#2517]
Hello insightface team! Thank you for such a wonderful library!

I have a problem and am not quite sure, what is the issue, but it seems that `antelopev2` model is not available for download right now:

```python
from insightface.app import FaceAnalysis
app = FaceAnalysis(name='antelopev2', root='./', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))
````

and I get the following error:

```
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
```

Could you please clarify, what is happening here? Maybe @nttstar can help with that?

**Comment by Neptune-Trojans** [comment]
Please see that page: https://github.com/deepinsight/insightface/tree/master/python-package

Name in bold is the default model pack. Auto means we can download the model pack through the python library directly.


You need to download the antelopev2 manually and put that inside .insightface folder.

**Comment by RadTechDad** [comment]
So according to that page, it seems there is only one model (the default one) available for download through the python library directly. Is there a reason the others are not available? Is there a reason the others are not on another public repository such as huggingface? I just don't like the fact that these files are being hosted on a google drive account.

I've manually downloaded all the models, would it be okay for me to put them on my huggingface account?

**Comment by ubros27** [comment]
ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev2
https://huggingface.co/MonsterMMORPG/tools/resolve/main/antelopev2.zip

**Comment by raunick** [comment]
opaa isso me ajudou muito !!! muito obg.

**Comment by 37OMKAR** [comment]
STILL NOT WORKING, COPIED THE FOLDER 

Prompt executed in 2.82 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
download_path: F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2
Downloading F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
!!! Exception during processing!!! Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
Traceback (most recent call last):
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

Prompt executed in 0.32 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
download_path: F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2
Downloading F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\models\insightface\models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
!!! Exception during processing!!! Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
Traceback (most recent call last):
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 217, in load_insight_face
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "F:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

**Comment by twang3** [comment]
> ComfyUI\models\insightface\models

Download antelopev2.zip and unzip it to ComfyUI\models\insightface\models. The model file should be located in ComfyUI\models\insightface\models\antelopev2, for example ComfyUI\models\insightface\models\antelopev2\1k3d68.onnx

**Comment by joramirez764** [comment]
In my case the folder was repeated in cascade ... simply delete 1 folder and pass the files ....
that is... something like this...
-- antelopev2
       -- antelopev2
             -- model files.
solution...
-- antelopev2
      -- model files.

**Comment by Posthumanit** [comment]
> In my case the folder was repeated in cascade ... simply delete 1 folder and pass the files .... that is... something like this... -- antelopev2 -- antelopev2 -- model files. solution... -- antelopev2 -- model files.

Thank you very much I was going crazy... sometimes the simple things you don't see are the most harmful...

**Comment by oojopentagonal** [comment]
I have a workflow that is looking at a antelopev2.onnx and the zip file has 5 onnx, doesn anyone knows how to solve this?

**Comment by cacard** [comment]
1, add log to  
![image](https://github.com/user-attachments/assets/e5af01bf-370e-4965-9f80-75cd7daeb2f4)

<img width="598" alt="image" src="https://github.com/user-attachments/assets/b3794e87-dc5e-450f-9ff7-af9c8231fbd6">

found that:
model_dir:checkpoints\misc\face_analysis\models
count:0

why 0? cause models/*onnux is null

so, we change to:
<img width="590" alt="image" src="https://github.com/user-attachments/assets/f3de2570-b0c8-41d3-808f-1a27973ca1ab">

work !!!

**Comment by vaclavmuller** [comment]
### Issue Description
When using ComfyUI with the PulidInsightFaceLoader node, the application downloads the `antelopev2.zip` file for the InsightFace models. However, the models inside the ZIP file are stored in a nested folder, which causes the loader to fail.

The `antelopev2.zip` file contains the ONNX models inside a subfolder. For example:
models/ antelopev2.zip/ antelopev2/ 1k3d68.onnx 2d106det.onnx ...

The application expects these `.onnx` files directly in the folder `models/insightface/antelopev2`. Users must manually move the files from the nested folder to the correct directory.

### Steps to Reproduce
1. Run ComfyUI with PulidInsightFaceLoader.
2. Let the application download and unpack `antelopev2.zip`.
3. Check the folder `models/insightface/antelopev2` and see that the `.onnx` files are inside a subfolder.

### Expected Behavior
The ONNX files from the ZIP should be unpacked directly into the `models/insightface/antelopev2` directory.

### Proposed Solution
The unpacking process should check for nested folders and move the files to the correct location automatically.

### Additional Information
I resolved this issue manually by moving the `.onnx` files from the nested folder to the `models/insightface/antelopev2` directory.

**Comment by GURSHARN219** [comment]
date 25/5/2025

today i face same in comfyui , this some details how i fix it

A:\AI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l  https://drive.google.com/file/d/1qXsQJ8ZT42_xSmWIYy85IcidpiZudOCB/view

A:\AI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\antelopev2  https://drive.google.com/file/d/18wEUfMNohBJ4K3Ly5wpTejPfDzp-8fI8/view?pli=1
https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip

usefull link : https://github.com/deepinsight/insightface/tree/master/python-package

optional
A:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\models\antelopev2
A:\AI\ComfyUI_windows_portable\python_embeded\insightface\models\antelopev2
A:\AI\ComfyUI_windows_portable\python_embeded\insightface\models\antelopev2




error (
Prompt executed in 15.17 seconds
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "A:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\pulid_comfyui\pulid.py", line 240, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 0.05 seconds
)
