### ISSUE TITLE
verification on my own data

### ISSUE THREAD

**Issue by cici-tan** [deepinsight/insightface#252]
I generated my own data using lfw2pack.py, and image size is 160x160.
But when I run verification.py, it popped out this error...

"expected [3,160,160], got [3,112,112]"

Traceback (most recent call last):
  File "verification.py", line 566, in <module>
    data_set = load_bin(path, image_size)
  File "verification.py", line 196, in load_bin
    data_list[flip][i][:] = img
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray/ndarray.py", line 437, in __setitem__
    self._set_nd_basic_indexing(key, value)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray/ndarray.py", line 691, in _set_nd_basic_indexing
    value.copyto(self)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray/ndarray.py", line 1876, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 25, in _copyto
  File "/usr/local/lib/python2.7/dist-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:54:06] src/operator/nn/./../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [3,160,160], got [3,112,112]

**Comment by nttstar** [comment]
what's your training data shape?

**Comment by nttstar** [comment]
You must keep the input shape consistent while doing training and inferencing. So you have to use 112x112 as input.

**Comment by cici-tan** [comment]
so should I cropped my input image to 112x112?

**Comment by nttstar** [comment]
right.

**Comment by heshao90** [comment]
@nttstar hi, what's the meaning of <nrof_classes> in property file?

**Comment by nttstar** [comment]
@heshao90 number of identities.
