### ISSUE TITLE
Somebody help pls! TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

### ISSUE THREAD

**Issue by BruceSun94** [deepinsight/insightface#2528]
2024-02-17 00:54:29,657 - ControlNet - [0;32mINFO[0m - Preview Resolution = 512
Traceback (most recent call last):
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 830, in face_id_plus
    face_embed, _ = g_insight_face_model.run_model(img)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 749, in run_model
    self.load_model()
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 741, in load_model
    self.model = FaceAnalysis(
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'
2024-02-17 00:54:58,276 - ControlNet - [0;32mINFO[0m - Preview Resolution = 512
Traceback (most recent call last):
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sd-webui-aki-v4.2\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 830, in face_id_plus
    face_embed, _ = g_insight_face_model.run_model(img)
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 749, in run_model
    self.load_model()
  File "C:\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\scripts\processor.py", line 741, in load_model
    self.model = FaceAnalysis(
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'
------------------------

**Comment by BruceSun94** [comment]
C:\sd-webui-aki-v4.2>pip show insightface
Name: insightface
Version: 0.7.3
Summary: InsightFace Python Library
Home-page: https://github.com/deepinsight/insightface
Author: InsightFace Contributors
Author-email: contact@insightface.ai
License: MIT
Location: c:\users\bruce\anaconda3\lib\site-packages
Requires: albumentations, cython, easydict, matplotlib, numpy, onnx, Pillow, prettytable, requests, scikit-image, scikit-learn, scipy, tqdm
Required-by:

**Comment by AliHamandy** [comment]
did you solve it yet i got the same error
