### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by ahn-heejin** [deepinsight/insightface#2555]
I'm having trouble understanding the specific error you're encountering while trying to train SCRFD using the Wider Face dataset from the provided link. To better assist you, could you please share the exact error message or describe the issue you're facing in more detail? This will help in identifying the cause and providing a solution.

------
$ CUDA_VISIBLE_DEVICES="0,1,2" PORT=29701 bash ./tools/dist_train.sh ./configs/scrfd/scrfd_34g.py 3

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Killing subprocess 237637
Killing subprocess 237638
Killing subprocess 237639
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=2', './configs/scrfd/scrfd_34g.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by satishjasthi** [comment]
duplicate of #2404
