### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by newbinxxxx** [deepinsight/insightface#2574]
Traceback (most recent call last):
  File "G:\ComfyUI_1228\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\ComfyUI_1228\\ComfyUI\\custom_nodes\\insightface\\__init__.py'

Cannot import G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface module for custom nodes: [Errno 2] No such file or directory: 'G:\\ComfyUI_1228\\ComfyUI\\custom_nodes\\insightface\\__init__.py'

**Comment by newbinxxxx** [comment]
Traceback (most recent call last):
  File "G:\ComfyUI_1228\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\ComfyUI_1228\\ComfyUI\\custom_nodes\\insightface\\__init__.py'

Cannot import G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface module for custom nodes: [Errno 2] No such file or directory: 'G:\\ComfyUI_1228\\ComfyUI\\custom_nodes\\insightface\\__init__.py'

[rgthree] Loaded 34 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\ComfyUI_1228\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "The harder I work, the luckier I get." - Samuel Goldwyn


Import times for custom nodes:
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI_TiledIPAdapter
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-FanYi
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-StableDiffusion3-API
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\comfy_sd_krita_plugin_nodes
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds (IMPORT FAILED): G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI_SimpleTiles
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: G:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI_essentials****

**Comment by newbinxxxx** [comment]
Traceback (most recent call last):
File "G:\ComfyUI_1228\ComfyUI\nodes.py", line 1876, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 936, in exec_module
File "", line 1073, in get_code
File "", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface\init.py'

Cannot import G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface module for custom nodes: [Errno 2] No such file or directory: 'G:\ComfyUI_1228\ComfyUI\custom_nodes\insightface\init.py'

why?
