### ISSUE TITLE
Error initializing face analysis model: in insightface 

### ISSUE THREAD

**Issue by Vinaygoudasp7** [deepinsight/insightface#2635]
Error initializing face analysis model: __init__() got an unexpected keyword argument 'provider_options'
Traceback (most recent call last):
  File "/home/trinity/face_recognization/face_detection_recognition1.py", line 35, in __init__
    self.model = FaceAnalysis(name='buffalo_s')
  File "/home/trinity/insight_facerec_venv/lib/python3.6/site-packages/insightface/app/face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "/home/trinity/insight_facerec_venv/lib/python3.6/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/home/trinity/insight_facerec_venv/lib/python3.6/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/home/trinity/insight_facerec_venv/lib/python3.6/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'provider_options'

i am running it on jetson nano devices of jetpack 4.4.1

**Comment by Vinaygoudasp7** [comment]
i was using the onnxruntime with version 1.4.0 but when i install 1.10.0 it works for me
