### ISSUE TITLE
pip install scrfd/requirements.txt Failed

### ISSUE THREAD

**Issue by fkw1993** [deepinsight/insightface#2699]
```shell
MacBook-Pro:bin kevin$ ./pip install -r  /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements.txt   -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: cython in /Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/build.txt (line 2)) (0.29.33)
Requirement already satisfied: numpy in /Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/build.txt (line 3)) (2.1.3)
Collecting albumentations>=0.3.2 (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/optional.txt (line 1))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b0/e5/466001d1f1567932d5ccd499287e31508f405d113fe97f961312d9a64597/albumentations-1.4.21-py3-none-any.whl (227 kB)
Collecting cityscapesscripts (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/optional.txt (line 2))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/20/5b/35876d039b50e75db470de097c2f0af78805be08b9120d3989c6e1905bf3/cityscapesScripts-2.2.4-py3-none-any.whl (473 kB)
Collecting imagecorruptions (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/optional.txt (line 3))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3e/40/ff4a79ad7ab6463fe2fde7912b71084a6606e33676078a50b40a3377112b/imagecorruptions-1.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.8 MB/s eta 0:00:00
Collecting mmlvis (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/optional.txt (line 4))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/09/f3/79cab651db7262b356fa5ab2859af6039d6c8cb0fdf577a04ae1bd99bd2d/mmlvis-10.5.3-py3-none-any.whl (13 kB)
Requirement already satisfied: matplotlib in /Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/runtime.txt (line 1)) (3.9.2)
Collecting mmpycocotools (from -r /Users/kevin/PycharmProjects/insightface/insightface/detection/scrfd/requirements/runtime.txt (line 2))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/99/51/1bc1d79f296347eeb2d1a2e0606885ab1e4682833bf275fd39c189952e26/mmpycocotools-12.0.3.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kevin/PycharmProjects/insightface/insightface/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7n/5y1fqbs55812lqrcc3d5g28h0000gn/T/pip-build-env-bxcj0kbx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7n/5y1fqbs55812lqrcc3d5g28h0000gn/T/pip-build-env-bxcj0kbx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/7n/5y1fqbs55812lqrcc3d5g28h0000gn/T/pip-build-env-bxcj0kbx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/7n/5y1fqbs55812lqrcc3d5g28h0000gn/T/pip-build-env-bxcj0kbx/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by fkw1993** [comment]
I have already installed numpy


```python
MacBook-Pro:bin kevin$ ./pip show numpy
Name: numpy
Version: 2.1.3
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: Copyright (c) 2005-2024, NumPy Developers.
 All rights reserved.

**Comment by kivicode** [comment]
Try running it with the `--no-build-isolation` flag
