### ISSUE TITLE
I tried running test.py to generate the embedding vector of the face.

### ISSUE THREAD

**Issue by anshumankmr97** [deepinsight/insightface#279]
I had this error.
`/home/anshuman/anaconda3/lib/python3.6/site-packages/skimage/__init__.py:60: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
[08:04:50] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[08:04:50] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
/home/anshuman/anaconda3/lib/python3.6/site-packages/mxnet/model.py:928: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  **kwargs)
[08:04:50] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[08:04:50] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[08:04:50] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[08:04:50] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[08:04:50] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[08:04:50] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    gender, age = model.get_ga(img)
  File "/home/anshuman/Documents/Repos/insightface/deploy/face_model.py", line 103, in get_ga
    self.ga_model.forward(db, is_train=False)
AttributeError: 'NoneType' object has no attribute 'forward'`

Did anyone else have this error? So basically the  line 
`    self.ga_model.forward(db, is_train=False) ` 
in face_model.py doesn't have any attribute forward, so does anyone know how to fix this?

**Comment by nttstar** [comment]
error from `self.ga_model.forward`
not `self.model.forward`

**Comment by anshumankmr97** [comment]
oh yeah my bad, its self.ga_model.forward

**Comment by anshumankmr97** [comment]
I think my issue was similar in nature to #272 , isn't it ?
