### ISSUE TITLE
about test the pre-trained models, error 'Module' object has no attribute 'feature'

### ISSUE THREAD

**Issue by xisi789** [deepinsight/insightface#287]
Traceback (most recent call last):
  File "E:/0-project/1-facerecognition/1-code/insightface-master/insightface-master/gluon/verification.py", line 365, in <module>
testing verification..
    acc1, std1, acc2, std2, xnorm, embeddings_list = test(ver_list[i], model, ctx, args.batch_size, args.nfolds)
  File "E:/0-project/1-facerecognition/1-code/insightface-master/insightface-master/gluon/verification.py", line 229, in test
    z = net.feature(x)
AttributeError: 'Module' object has no attribute 'feature'

**Comment by nttstar** [comment]
Do not use gluon now.

**Comment by xisi789** [comment]
Ok, problem solved. Thank you!

**Comment by HannibalAPE** [comment]
sorry to bother you. Can you tell how to fix this problem? What does 'Do not use gluon now' mean? @xisi789 Thanks in advance.
