### ISSUE TITLE
Does Insightface have a strict requirement for input images?

### ISSUE THREAD

**Issue by Lane565** [deepinsight/insightface#400]
Yeah, I developed a small FR system based on Insightface. But lately, for few times when I run the system to recognize self-collected images, the system encounter an error. It seems there is something wrong with the input images, especially for those side faces or low-resolution faces. Is that normal for Insightface ? 
 Come and help me ,who is just a sophomore. Thanks a lot !!!

Below are the console information of my python project:
Traceback (most recent call last):
  File "E:/xiang/Moon/face_platform/gui/recognize_faces.py", line 37, in <module>
    form.append(model.get_feature(model.get_input(image)))
  File "E:\xiang\Moon\face_platform\Insightface\face_model.py", line 114, in get_feature
    self.model.forward(db, is_train=False)
  File "D:\Python352\lib\site-packages\mxnet\module\module.py", line 610, in forward
    self.reshape(new_dshape, new_lshape)
  File "D:\Python352\lib\site-packages\mxnet\module\module.py", line 471, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "D:\Python352\lib\site-packages\mxnet\module\executor_group.py", line 382, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "D:\Python352\lib\site-packages\mxnet\module\executor_group.py", line 358, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "D:\Python352\lib\site-packages\mxnet\executor.py", line 402, in reshape
    arg_shapes, _, aux_shapes = self._symbol.infer_shape(**kwargs)
  File "D:\Python352\lib\site-packages\mxnet\symbol\symbol.py", line 990, in infer_shape
infer_shape error. Arguments:
  data: (1,)
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "D:\Python352\lib\site-packages\mxnet\symbol\symbol.py", line 1120, in _infer_shape_impl
    ctypes.byref(complete)))
  File "D:\Python352\lib\site-packages\mxnet\base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator conv_1_conv2d: [19:18:09] C:\Jenkins\workspace\mxnet-tag\mxnet\src\operator\nn\convolution.cc:143: Check failed: dshp.ndim() == 4U (1 vs. 4) Input data should be 4D in batch-num_filter-y-x

Process finished with exit code 1

**Comment by suyali** [comment]
hello，Have you solved the problem? It also occurs to me when I run deploy/test.py?.

**Comment by suyali** [comment]
sorry,I knew the reason! the picture you input make sense!

**Comment by Lane565** [comment]
For me, everything goes on smoothly when the input image is standard face. But not for side face images.

**Comment by Lane565** [comment]
![r cdsz9 qe8pn4 63n_7r](https://user-images.githubusercontent.com/16103351/47996236-d00e1b80-e132-11e8-99fc-47d7daa01b46.png)
