### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by Chunl** [deepinsight/insightface#403]
Hi there,

There is something wrong during the mobile face net training. I followed the set up module in ReadMe.

Training command line:
python -u train_softmax.py --network m1 --loss-type 0 --data-dir ../datasets/faces_ms1m_112x112 --prefix ../model-m1-softmax

Error:

Traceback (most recent call last):
  File "train_softmax.py", line 503, in <module>
    main()
  File "train_softmax.py", line 500, in main
    train_net(args)
  File "train_softmax.py", line 494, in train_net
    epoch_end_callback = epoch_cb )
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\module\base_module.py", line 498, in fit
    for_training=True, force_rebind=force_rebind)
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\module\executor_group.py", line 375, in bind_exec
    shared_group))
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\module\executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\Program Files\Anaconda3\envs\py27\lib\site-packages\mxnet\symbol\symbol.py", line 1528, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
softmax_label: (1,)
[18:05:24] C:\Jenkins\workspace\mxnet-tag\mxnet\src\storage\storage.cc:119: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: no CUDA-capable device is detected

What did i miss? Thank you in advance.

**Comment by nttstar** [comment]
Set CUDA_VISIBLE_DEVICES

**Comment by Chunl** [comment]
Thanks for your response. 

I have set the CUDA_VISIBLE_DEVICES, but it seems that doesn't work.
The training on CPU works well.

**Comment by zzpfox** [comment]
I have the same problem as you. Has it been solved?

**Comment by wting861006** [comment]
me too.I run it at windows10.Does it related?

**Comment by Talgin** [comment]
Hi, could you answer the above question? 
OS: Windows 10
Cuda: 9.0
mxnet_cu90

**Comment by TedSYt** [comment]
Same problems! I don't know were Jenkins comes from
