### ISSUE TITLE
ms1m+vgg dataset_merge?

### ISSUE THREAD

**Issue by yang0817manman** [deepinsight/insightface#448]
hello,I have trained SE-Res50 with ms1m dataset, but I want to finetune the model of " SE-Res50" with the "ms1m+vgg2" dataset. I try to merge ms1m dataset and vgg2 dataset some times by the function of "dataset_merge.py", but i cannot merge datasets successfully.Can you help me or share your dataset of "ms1m+vgg2"?Thanks very a lot.
What's more, I merged our datasets by the function of "dataset_merge.py", the error appeared as following:"Traceback (most recent call last):
  File "/home/algorithm-5/insightface/src/data/dataset_merge.py", line 293, in <module>
    main(args)
  File "/home/algorithm-5/insightface/src/data/dataset_merge.py", line 128, in main
    assert header.flag>0
AssertionError"
  What is meanings of "  for ds_id in xrange(len(rec_list)):
    id_list = []
    imgrec = rec_list[ds_id]
    s = imgrec.read_idx(0)
    header, _ = mx.recordio.unpack(s)
    assert header.flag>0
    print('header0 label', header.label)
    header0 = (int(header.label[0]), int(header.label[1]))
    #assert(header.flag==1)
    imgidx = range(1, int(header.label[0]))
    id2range = {}
    seq_identity = range(int(header.label[0]), int(header.label[1]))"?
Thanks!

**Comment by yang0817manman** [comment]
HI, I want to merge datasets successfully but I am confused to the code of "dataset_merge.py" 's command lines
" parser.add_argument('--param1', default=0.3, type=float, help='')
  parser.add_argument('--param2', default=0.4, type=float, help='')"
what are meanings of the above "'--param1' and '--param2' ?Is it removed same id and clean datasets?
