### ISSUE TITLE
when i train as the readme,i have this issues and i can not fix this problem. can i get some help from you and i will appreciate it.

### ISSUE THREAD

**Issue by Vincent630** [deepinsight/insightface#452]
[11:07:42] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:109: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "train_softmax.py", line 503, in <module>
    main()
  File "train_softmax.py", line 500, in main
    train_net(args,)
  File "train_softmax.py", line 494, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/wenguang.wang/anaconda3/envs/python2/lib/python2.7/site-packages/mxnet/module/base_module.py", line 526, in fit
    self.update()
  File "/home/wenguang.wang/anaconda3/envs/python2/lib/python2.7/site-packages/mxnet/module/module.py", line 664, in update
    self._kvstore, self._exec_group.param_names)
  File "/home/wenguang.wang/anaconda3/envs/python2/lib/python2.7/site-packages/mxnet/model.py", line 153, in _update_params_on_kvstore
    kvstore.push(name, grad_list, priority=-index)
  File "/home/wenguang.wang/anaconda3/envs/python2/lib/python2.7/site-packages/mxnet/kvstore.py", line 234, in push
    self.handle, mx_uint(len(ckeys)), ckeys, cvals, ctypes.c_int(priority)))
  File "/home/wenguang.wang/anaconda3/envs/python2/lib/python2.7/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:08:07] src/storage/./pooled_storage_manager.h:119: cudaMalloc failed: out of memory

**Comment by oukohou** [comment]
@Vincent630 as you can see from the last line, "out of memory", maybe you should use a smaller batch size.
