### ISSUE TITLE
local variable 'fc7' referenced before assignment

### ISSUE THREAD

**Issue by Royzon** [deepinsight/insightface#528]
when I changed as below , I got this error, is there anybody can help me to solve this error?
`loss.combined = edict()
loss.combined.loss_name = 'combined'
loss.combined.loss_s = 64.0
loss.combined.loss_m1 = 1.0
loss.combined.loss_m2 = 0.3
loss.combined.loss_m3 = 0.2

default.loss = 'combined'
`

**Comment by nttstar** [comment]
loss name should be 'margin_softmax'

**Comment by Royzon** [comment]
sorry. I'm so stupid. but when I reset to your default code, just change default loss type, there are also some errors as below:


1、default.loss = 'margin_softmax'
Traceback (most recent call last):
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/train.py", line 402, in <module>
    main()
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/train.py", line 398, in main
    args = parse_args()
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/train.py", line 79, in parse_args
    generate_config(args.network, args.dataset, args.loss)
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/config.py", line 183, in generate_config
    for k, v in loss[_loss].items():
KeyError: 'margin_softmax'


2、default.loss = 'triplet'  or  'triplet'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sugon/.local/lib/python2.7/site-packages/mxnet/io.py", line 401, in prefetch_func
    self.next_batch[i] = self.iters[i].next()
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/triplet_image_iter.py", line 480, in next
    self.reset()
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/triplet_image_iter.py", line 390, in reset
    self.select_triplets()
  File "/home/sugon/face_rec/Insightface/insightface_new/recognition/triplet_image_iter.py", line 253, in select_triplets
    self.mx_model.forward(db, is_train=False)
  File "/home/sugon/.local/lib/python2.7/site-packages/mxnet/module/module.py", line 591, in forward
    assert self.binded and self.params_initialized
AssertionError

/home/sugon/.local/lib/python2.7/site-packages/mxnet/module/base_module.py:504: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.0166666666667). Is this intended?
  optimizer_params=optimizer_params)

**Comment by nttstar** [comment]
```
combined.loss_name = 'margin_softmax'
```

```
train.py --loss combined
```

**Comment by nttstar** [comment]
Please firstly check `sample_config.py` and `README`
