### ISSUE TITLE
python3.6 train --loss triplet

### ISSUE THREAD

**Issue by wangxm345566462** [deepinsight/insightface#547]
```
gpu num: 1
prefix ./models\y1-triplet-emore\model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=60, ckpt=3, ctx_num=1, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='triplet', lr=0.005, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='y1', per_batch_size=60, pretrained='models/y1-arcface-emore/model', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'bn_mom': 0.9, 'workspace': 256, 'emb_size': 128, 'ckpt_embedding': True, 'net_se': 0, 'net_act': 'prelu', 'net_unit': 3, 'net_input': 1, 'net_output': 'GDC', 'net_multiplier': 1.0, 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'fc7_lr_mult': 1.0, 'fc7_wd_mult': 1.0, 'fc7_no_bias': False, 'max_steps': 0, 'data_rand_mirror': True, 'data_cutoff': False, 'data_color': 0, 'data_images_filter': 0, 'loss_name': 'triplet', 'images_per_identity': 5, 'triplet_alpha': 0.3, 'triplet_bag_size': 7200, 'triplet_max_ap': 0.0, 'per_batch_size': 60, 'lr': 0.05, 'net_name': 'fmobilefacenet', 'dataset': 'emore', 'dataset_path': '../datasets/faces_emore', 'num_classes': 85742, 'image_shape': [112, 112, 3], 'loss': 'triplet', 'network': 'y1', 'num_workers': 1}
loading models/y1-arcface-emore/model 1
in_network {'bn_mom': 0.9, 'workspace': 256, 'emb_size': 128, 'ckpt_embedding': True, 'net_se': 0, 'net_act': 'prelu', 'net_unit': 3, 'net_input': 1, 'net_output': 'GDC', 'net_multiplier': 1.0, 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'fc7_lr_mult': 1.0, 'fc7_wd_mult': 1.0, 'fc7_no_bias': False, 'max_steps': 0, 'data_rand_mirror': True, 'data_cutoff': False, 'data_color': 0, 'data_images_filter': 0, 'loss_name': 'triplet', 'images_per_identity': 5, 'triplet_alpha': 0.3, 'triplet_bag_size': 7200, 'triplet_max_ap': 0.0, 'per_batch_size': 60, 'lr': 0.05, 'net_name': 'fmobilefacenet', 'dataset': 'emore', 'dataset_path': '../datasets/faces_emore', 'num_classes': 85742, 'image_shape': [112, 112, 3], 'loss': 'triplet', 'network': 'y1', 'num_workers': 1}
INFO:root:loading recordio ../datasets/faces_emore\train.rec...
header0 label [ 5822654.  5908396.]
id2range 85742
5822653
rand_mirror True
5 12 6
triplet_seq 427507
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver lfw
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
loading bin 13000
(14000, 3, 112, 112)
ver cfp_fp
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [100000, 160000, 220000]
call reset()
eval 7200 images.. 0
triplet time stat [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\io.py", line 401, in prefetch_func
    self.next_batch[i] = self.iters[i].next()
  File "D:\projects\python\insightface\recognition\triplet_image_iter.py", line 480, in next
    self.reset()
  File "D:\projects\python\insightface\recognition\triplet_image_iter.py", line 391, in reset
    self.select_triplets()
  File "D:\projects\python\insightface\recognition\triplet_image_iter.py", line 254, in select_triplets
    self.mx_model.forward(db, is_train=False)
  File "C:\Users\**\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\module\module.py", line 591, in forward
    assert self.binded and self.params_initialized
AssertionError

C:\Users\**\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\module\base_module.py:504: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (1.0 vs. 0.016666666666666666). Is this intended?
  optimizer_params=optimizer_params)

```

**Comment by wangxm345566462** [comment]
```
    model = mx.mod.Module(
        context=ctx,
        symbol=sym,
    )
    model.bind([("data", (args.batch_size, args.image_channel, image_size[0], image_size[1]))], [("softmax_label", (args.batch_size,))])
```
