### ISSUE TITLE
 MXNetError:cudaMalloc failed: out of memory when loading the model

### ISSUE THREAD

**Issue by estarpro** [deepinsight/insightface#571]
Hello,@nttstar I trained the model successfully,but when I tried to load the pretrained model ,it threw a wrong message.My batch_size is 16.Here is the message:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    mod.bind(for_training=False, data_shapes=[('data', (1, 3, 112, 112))])
  File "/home/cbd109/applications/anaconda3/envs/pyzhc27/lib/python2.7/site-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/home/cbd109/applications/anaconda3/envs/pyzhc27/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/cbd109/applications/anaconda3/envs/pyzhc27/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/home/cbd109/applications/anaconda3/envs/pyzhc27/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/cbd109/applications/anaconda3/envs/pyzhc27/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 1528, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
[13:36:17] src/storage/./pooled_storage_manager.h:143: cudaMalloc failed: out of memory

**Comment by estarpro** [comment]
And I also met the same problem when I tried to execute code from folder deploy/test.py.I think maybe I should use package mxnet-cu80 instead of package mxnet-cu100.Does this really matter?

**Comment by nttstar** [comment]
depends on your cuda version

**Comment by mstfldmr** [comment]
I have Cuda 10 and mxnet-cu90mkl v1.4.0. I get the same error.

**Comment by bartengine27** [comment]
can you change the batch size in config.py?

**Comment by sahil12051994** [comment]
Reducing the batch size solves the problem, I did it to 4. Cuda - release 9.2, V9.2.148 / Python-3
