### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by xinxliu** [deepinsight/insightface#592]
Platform information:

- Python 2.7
- MXNet 1.4

Hi, I met the following error when I ran the `train.py` under `insightface/recognition`. I am sure I use the **recommended dataset MS1M-ArcFace** from the  [baidu source](https://pan.baidu.com/s/1S6LJZGdqcZRle1vlcMzHOQ).

> Traceback (most recent call last):
  File "train.py", line 366, in <module>
    main()
  File "train.py", line 363, in main
    train_net(args)
  File "train.py", line 231, in train_net
    images_filter        = config.data_images_filter,
  File "/home/liuxx/work/insightface/recognition/image_iter.py", line 42, in __init__
    header, _ = recordio.unpack(s)
  File "/home/liuxx/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet/recordio.py", line 416, in unpack
    header = IRHeader(*struct.unpack(_IR_FORMAT, s[:_IR_SIZE]))
TypeError: 'NoneType' object has no attribute '__getitem__'

Then I manually load the dataset:
`>>> imgrec = mx.recordio.MXIndexedRecordIO('datasets/faces_emore/train.idx', 'datasets/faces_emore/train.rec', 'r')`
 `>>> s = imgrec.read_idx(0)`
`>>>s is None`
`True`

The result of `s is None` is **True**. Hence is there something wrong with the dataset?

**Comment by xinxliu** [comment]
Now I know what's wrong. Unzipping the .zip file under Ubuntu may cause CRC error when the zipped file is larger than 4GB. Unzipping it under Windows can solve this.
