### ISSUE TITLE
train_triplet error: Incompatible attr in node _minus1 at 1-th input

### ISSUE THREAD

**Issue by bill-lin** [deepinsight/insightface#607]
Hi,

I am testing using train_triplet to finetune a pre-trained model (LResNet100E-IR,ArcFace@ms1m-refine-v2), however I got an error ` Incompatible attr in node _minus1 at 1-th input: expected [3,512], got [4,512]`.
Does anyone have an idea about how to fix it?

Many thanks

Full error log:
```
use cpu
num_layers 100
image_size [112, 112]
num_classes 1000
Called with argument: Namespace(batch_size=10, ckpt=3, ctx_num=1, cutoff=0, data_dir='/images/training_data_insight', emb_size=512, end_epoch=100000, image_channel=3, image_h=112, image_w=112, images_per_identity=5, loss_type=1, lr=0.005, lr_steps='', max_steps=0, mom=0.9, network='r100', noise_sgd=0.0, num_classes=1000, num_layers=100, per_batch_size=10, prefix='../model/model', pretrained='./models/face-reco-model-r100-ii/model,0', rand_mirror=1, target='lfw,cfp_fp,agedb_30', triplet_alpha=0.3, triplet_bag_size=3600, triplet_max_ap=0.0, use_deformable=0, verbose=2000, version_act='prelu', version_input=1, version_output='E', version_se=0, version_unit=3, wd=0.0005)
loading ['./models/face-reco-model-r100-ii/model', '0']
[14:27:08] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[14:27:08] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
INFO:root:loading recordio /images/zaw-photos-1000users-output/insight/training_data_insight/train.rec...
header0 label [19997. 20997.]
id2range 1000
19996
rand_mirror 1
5 2 600
triplet_seq 4994
lr_steps [1000000000]
Traceback (most recent call last):
  File "src/train_triplet.py", line 401, in <module>
    main()
  File "src/train_triplet.py", line 398, in main
    train_net(args)
  File "src/train_triplet.py", line 392, in train_net
    epoch_end_callback = epoch_cb )
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 498, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 1528, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (10, 3, 112, 112)
softmax_label: (10,)
Error in operator _minus1: [14:27:09] /home/travis/build/dmlc/mxnet-distro/mxnet-build/3rdparty/mshadow/../../src/operator/tensor/../elemwise_op_common.h:133: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _minus1 at 1-th input: expected [3,512], got [4,512]
```

**Comment by bill-lin** [comment]
seems it's batch size problem

**Comment by WIll-Xu35** [comment]
Hi, how do you set your batch size and triplet bag size accordingly? I'm trying to finetune using a very small dataset (around 250 face images), no matter what value I set for batch size and triplet bag size, there is always the error you encountered

**Comment by XianYuZhiWang** [comment]
batch size % 3 must = 0
