### ISSUE TITLE
recognition/train.py loss选择triplet报错

### ISSUE THREAD

**Issue by wting861006** [deepinsight/insightface#696]
>C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\face\insightface-master\recognition>python -u train.py --network r100 --loss triplet --dataset emore --per-batch-size 50 --lr 0.005 --pretrained D:\insightface\models\r100-arcface-emore\model --pretrained-epoch 1

输出如下错误。loss选择arcface或softmax不会报错。
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
gpu num: 4
prefix ./models\r100-triplet-emore\model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=200, ckpt=3, ctx_num=4, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='triplet', lr=0.005, lr_steps='50000,80000,110000', models_root='./models', mom=0.9, network='r100', per_batch_size=50, pretrained='D:\\insightface\\models\\r100-arcface-emore\\model', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'bn_mom': 0.9, 'workspace': 256, 'emb_size': 512, 'ckpt_embedding': False, 'net_se': 0, 'net_act': 'prelu', 'net_unit': 3, 'net_input': 1, 'net_blocks': [1, 4, 6, 2], 'net_output': 'E', 'net_multiplier': 1.0, 'val_targets': ['agedb_30'], 'ce_loss': True, 'fc7_lr_mult': 1.0, 'fc7_wd_mult': 1.0, 'fc7_no_bias': False, 'max_steps': 0, 'data_rand_mirror': True, 'data_cutoff': False, 'data_color': 0, 'data_images_filter': 0, 'count_flops': True, 'memonger': False, 'loss_name': 'triplet', 'images_per_identity': 5, 'triplet_alpha': 0.3, 'triplet_bag_size': 7200, 'triplet_max_ap': 0.0, 'per_batch_size': 50, 'lr': 0.05, 'net_name': 'fresnet', 'num_layers': 100, 'dataset': 'emore', 'dataset_path': 'F:\\facedataset\\faces_emore', 'num_classes': 85742, 'image_shape': [112, 112, 3], 'loss': 'triplet', 'network': 'r100', 'num_workers': 1, 'batch_size': 200}
loading D:\insightface\models\r100-arcface-emore\model 1
0 1 E 3 prelu False
Network FLOPs: 24.2G
INFO:root:loading recordio F:\facedataset\faces_emore\train.rec...
header0 label [5822654. 5908396.]
id2range 85742
5822653
rand_mirror True
5 10 6
triplet_seq 427507
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver agedb_30
lr_steps [50000, 80000, 110000]
call reset()
eval 7200 images.. 0
triplet time stat [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1523, in simple_bind
    ctypes.byref(exe_handle)))
  File "C:\Anaconda3\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator _minus0: [14:39:52] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)) Incompatible attr in node _minus0 at 1-th input: expected [16,512], got [17,512]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 374, in main
    train_net(args)
  File "train.py", line 369, in train_net
    epoch_end_callback = epoch_cb )
  File "C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py", line 499, in fit
    for_training=True, force_rebind=force_rebind)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 375, in bind_exec
    shared_group))
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (50, 3, 112, 112)
softmax_label: (50,)
Error in operator _minus0: [14:39:52] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)) Incompatible attr in node _minus0 at 1-th input: expected [16,512], got [17,512]

**Comment by eguoguo321** [comment]
看最后一行，貌似是你清理掉fc7的数据？
expected [16,512], got [17,512]
愿模型是16类，你输入了17类
我遇到过类似的，用的哪个modelsilm解决了

**Comment by wting861006** [comment]
> 看最后一行，貌似是你清理掉fc7的数据？
> expected [16,512], got [17,512]
> 愿模型是16类，你输入了17类
> 我遇到过类似的，用的哪个modelsilm解决了

@eguoguo321 我想可能是我为了微调模型，在congfig.py文件里面设置config.ckpt_embedding = False导致。当我将这个参数改为True，出现了另外一个错误，请问你遇到过吗？
eval 7200 images.. 0
triplet time stat [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py:505: UserWarning: Optimizer created manually outside Module but rescale_grad is not normalized to 1.0/batch_size/num_workers (0.25 vs. 0.004166666666666667). Is this intended?
  optimizer_params=optimizer_params)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\mxnet\io\io.py", line 397, in prefetch_func
    self.next_batch[i] = self.iters[i].next()
  File "C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\face\insightface-master\recognition\triplet_image_iter.py", line 480, in next
    self.reset()
  File "C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\face\insightface-master\recognition\triplet_image_iter.py", line 390, in reset
    self.select_triplets()
  File "C:\Users\wangting\iCloudDrive\Pycharm\DeepLearning\face\insightface-master\recognition\triplet_image_iter.py", line 268, in select_triplets
    embeddings = sklearn.preprocessing.normalize(embeddings)
  File "C:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py", line 1412, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by eguoguo321** [comment]
没遇到过。。。但是看第一个抱错应该是类别fc7类别不同的问题吧，然后你说之前ckpt——embedding是false，那你的pretrain模型应该是包含fc7的，你现在改成true但是用的pretrained模型的fc7还是没变。
要不还是先改成false，然后移除fc7试试。

```cmd
Traceback (most recent call last):
  File "train_triplet.py", line 411, in <module>
    main()
  File "train_triplet.py", line 408, in main
    train_net(args)
  File "train_triplet.py", line 278, in train_net
    mx_model             = model,
  File "/opt/app/OCR/face-for-train/insightface/src/triplet_image_iter.py", line 48, in __init__
    assert header.flag>0
```
头疼，我也是用的别的loss都ok，想试试triplet的时候出了问题

**Comment by qianchen94** [comment]
> 没遇到过。。。但是看第一个抱错应该是类别fc7类别不同的问题吧，然后你说之前ckpt——embedding是false，那你的pretrain模型应该是包含fc7的，你现在改成true但是用的pretrained模型的fc7还是没变。
> 要不还是先改成false，然后移除fc7试试。
> 
> ```batchfile
> Traceback (most recent call last):
>   File "train_triplet.py", line 411, in <module>
>     main()
>   File "train_triplet.py", line 408, in main
>     train_net(args)
>   File "train_triplet.py", line 278, in train_net
>     mx_model             = model,
>   File "/opt/app/OCR/face-for-train/insightface/src/triplet_image_iter.py", line 48, in __init__
>     assert header.flag>0
> ```
> 
> 头疼，我也是用的别的loss都ok，想试试triplet的时候出了问题

我也遇到了这个问题 解决了么

**Comment by 2151330** [comment]
@wting861006 I have encountered the same problem as your first one. I know you have solved it. Could you please tell me the way.Thanks a lot.
![image](https://user-images.githubusercontent.com/41284417/62698790-95fade80-ba10-11e9-9ea5-2c79e3e440bc.png)
