### ISSUE TITLE
Has anyone successfully ran /gender-age/test.py ?What is the specific version of skimage?

### ISSUE THREAD

**Issue by Dawning23** [deepinsight/insightface#752]
When I run `/gender-age/test.py` I get an error  
```
Traceback (most recent call last):
  File "/home/zbh/Projects/insightface/gender-age/test.py", line 1, in <module>
    import face_model
  File "/home/zbh/Projects/insightface/gender-age/face_model.py", line 21, in <module>
    import face_preprocess
  File "/home/zbh/Projects/insightface/gender-age/../src/common/face_preprocess.py", line 4, in <module>
    from skimage import transform as trans
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/skimage/__init__.py", line 167, in <module>
    from .util.dtype import (img_as_float32,
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/skimage/util/__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/dask/array/__init__.py", line 5, in <module>
    from .core import (Array, block, concatenate, stack, from_array, store,
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/dask/array/core.py", line 29, in <module>
    from . import chunk
  File "/home/zbh/Anaconda3/envs/age/lib/python2.7/site-packages/dask/array/chunk.py", line 73, in <module>
    nancumprod = npcompat.nancumprod
AttributeError: 'module' object has no attribute 'nancumprod'
```

This is my specific version in the virtual environment.    
```
# Name                    Version                   Build  Channel
backports                 1.0                        py_2    anaconda
backports.functools_lru_cache 1.5                        py_2    anaconda
backports_abc             0.5                        py_0    anaconda
blas                      1.0                         mkl    defaults
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.3.9                 py27_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.1.1                      py_0    anaconda
cudatoolkit               9.0                  h13b8566_0    defaults
cycler                    0.10.0                   py27_0    anaconda
cytoolz                   0.9.0.1          py27h14c3975_1    anaconda
dask-core                 1.2.2                      py_0    anaconda
dbus                      1.13.6               h746ee38_0    anaconda
decorator                 4.4.0                    py27_1    anaconda
easydict                  1.9                        py_0    conda-forge
expat                     2.2.6                he6710b0_0    anaconda
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
functools32               3.2.3.2                  py27_1    anaconda
futures                   3.2.0                    py27_0    anaconda
glib                      2.56.2               hd408876_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
harfbuzz                  0.9.39                        1    defaults
hdf5                      1.8.17                        2    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      pypi_0    pypi
imageio                   2.5.0                    py27_0    anaconda
intel-openmp              2019.4                      243    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.1.0            py27he6710b0_0    anaconda
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.10               h2733197_2    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                he19cac6_0    defaults
matplotlib                2.2.3            py27hb69df0a_0    anaconda
matplotlib-base           2.2.3            py27h60b886d_1    conda-forge
mkl                       2019.4                      243    defaults
mxnet-cu90                1.4.1                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.2                      py27_1    anaconda
numpy                     1.14.6                   pypi_0    pypi
olefile                   0.46                     py27_0    anaconda
opencv3                   3.2.0               np111py27_0    menpo
openssl                   1.1.1b               h14c3975_1    conda-forge
pcre                      8.43                 he6710b0_0    defaults
pillow                    6.0.0            py27h34e0f95_0    anaconda
pip                       19.1.1                   py27_0    defaults
pixman                    0.38.0               h7b6447c_0    defaults
pyparsing                 2.4.0                      py_0    anaconda
pyqt                      5.9.2            py27h22d08a2_1    anaconda
python                    2.7.16               h9bab390_0    defaults
python-dateutil           2.8.0                    py27_0    anaconda
python-graphviz           0.8.4                    pypi_0    pypi
pytz                      2019.1                     py_0    anaconda
pywavelets                1.0.3            py27hdd07704_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.14.2           py27hf484d3e_1    conda-forge
scikit-learn              0.20.3           py27hd81dba3_0    defaults
scipy                     1.2.1            py27h7c811a0_0    defaults
setuptools                41.0.1                   py27_0    defaults
singledispatch            3.4.0.3                  py27_0    anaconda
sip                       4.19.13          py27he6710b0_0    anaconda
six                       1.12.0                   py27_0    anaconda
sqlite                    3.28.0               h7b6447c_0    defaults
subprocess32              3.5.4            py27h7b6447c_0    anaconda
tk                        8.6.9             hed695b0_1002    conda-forge
toolz                     0.9.0                    py27_0    anaconda
tornado                   5.1.1            py27h7b6447c_0    anaconda
urllib3                   1.25.3                   pypi_0    pypi
wheel                     0.33.4                   py27_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

Does anyone know the version that makes it run?

@nttstar  look forward to your reply

**Comment by clhne** [comment]
scikit-image                  0.14.2
successfully.
