### ISSUE TITLE
RetinaFace test.py RuntimeError: softmax_label is not presented

### ISSUE THREAD

**Issue by Chenyangzh** [deepinsight/insightface#755]
### After everything is set well, I start to run the demo test.py. But met this type of error:
[32, 16, 8] {'32': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (32, 16)}, '8': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (2, 1)}, '16': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (8, 4)}}
[14:02:42] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[14:02:42] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
means [0. 0. 0.]
use_landmarks False
sym size: 1
Traceback (most recent call last):
  File "./insightface-master/RetinaFace/test.py", line 15, in <module>
    detector = RetinaFace('./model/imagenet-resnet-152/resnet-152', 0, gpuid, 'net3')
  File "./insightface-master/RetinaFace/retinaface.py", line 139, in __init__
    self.model.set_params(arg_params, aux_params)
  File "~/.virtualenvs/mxnet_py2/local/lib/python2.7/site-packages/mxnet/module/module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "~/.virtualenvs/mxnet_py2/local/lib/python2.7/site-packages/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "~/.virtualenvs/mxnet_py2/local/lib/python2.7/site-packages/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: softmax_label is not presented

### I found solutions on some webpages like:
Adding `arg_params['softmax_label'] = mx.nd.array([0])` before `self.model.set_params(arg_params, aux_params)`

### After doing that another error occurs:
[32, 16, 8] {'32': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (32, 16)}, '8': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (2, 1)}, '16': {'ALLOWED_BORDER': 9999, 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'SCALES': (8, 4)}}
[14:03:23] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[14:03:23] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
means [0. 0. 0.]
use_landmarks False
sym size: 1
(1104, 736, 3)
('im_scale', 1.391304347826087)
[14:03:24] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "/home/zhaocy/chenyang/insightface_chenyang/insightface-master/RetinaFace/test.py", line 37, in <module>
    faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
  File "/home/zhaocy/chenyang/insightface_chenyang/insightface-master/RetinaFace/retinaface.py", line 229, in detect
    scores = scores[:, self._num_anchors['stride%s'%s]:, :, :]
IndexError: too many indices for array

### Anyone can explain these?

**Comment by levotrea** [comment]
Hello,

as "scores" seems to be of dimension 2, I tried removing the last two colons ( `scores = scores[:, self._num_anchors['stride%s'%s]:]` ), which got rid of this error, but I'm really not sure this is the way to go... Better wait for an official answer.

Also, I still got an error afterwards (if some are in the same case) :

Traceback (most recent call last):
  File "test.py", line 34, in <module>
    faces, landmarks = detector.detect(img, thresh, scales=scales, do_flip=flip)
  File "/xxx/insightface-master/RetinaFace/retinaface.py", line 239, in detect
    bbox_deltas = net_out[idx].asnumpy()
IndexError: list index out of range

The variable net_out is of length 1 and idx = 1, which raises this IndexError. I don't want to open an issue for this second error though, as it may be a consequence of the first error that we got.

**Comment by levotrea** [comment]
Hello again,

I think I found the issue ! In my case, I used the resnet-50 model for [training](https://github.com/deepinsight/insightface/blob/master/RetinaFace/README.md#training) that is given in the README , but using the [pretrained model](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0) given in the [Models](https://github.com/deepinsight/insightface/blob/master/RetinaFace/README.md#models) section just below worked like a charm for the test.py script.

It seems like you're using the resnet-152 which is also provided in the training section, so I hope this will solve your issue as well.

**Comment by xingha** [comment]
i got this error,

  File "/insightface/RetinaFace/test.py", line 15, in <module>
    detector = RetinaFace('./model/R152/resnet-152', 0, gpuid, 'net3')
  File "/insightface/RetinaFace/retinaface.py", line 139, in __init__
    self.model.set_params(arg_params, aux_params)
  File "/maxnet_py3/lib/python3.6/site-packages/mxnet/module/module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "/maxnet_py3/lib/python3.6/site-packages/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "/maxnet_py3/lib/python3.6/site-packages/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: softmax_label is not presented

**Comment by levotrea** [comment]
As answered by @nttstar in #760 :

> You may download the wrong models. Pre-trained models under `Train` section is just used for training and parameters initialization. 

which is also what I explained in my previous answer, if you just want to use test.py without training a model beforehand, then you have to use a pretrained model : [https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0).

You will have to place the model in the `models` folder and modify the `detector` line in test.py : `detector = RetinaFace("/xxx/insightface-master/models/retinaface-R50/R50", 0, gpuid, 'net3')`.

**Comment by levotrea** [comment]
Duplicate of #760

**Comment by xingha** [comment]
@levotrea ,
Thanks for your help.

**Comment by Chenyangzh** [comment]
Thanks for all of your help!

**Comment by mtydmm** [comment]
> As answered by @nttstar in #760 :
> 
> > You may download the wrong models. Pre-trained models under `Train` section is just used for training and parameters initialization.
> 
> which is also what I explained in my previous answer, if you just want to use test.py without training a model beforehand, then you have to use a pretrained model : https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0.
> 
> You will have to place the model in the `models` folder and modify the `detector` line in test.py : `detector = RetinaFace("/xxx/insightface-master/models/retinaface-R50/R50", 0, gpuid, 'net3')`, where "xxx" is the path to your insightface-master folder.

thanks
