### ISSUE TITLE
下载的glint数据集貌似有问题

### ISSUE THREAD

**Issue by weixin00** [deepinsight/insightface#893]
INFO:root:loading recordio /data/puke/face/faces_glint/train.rec...
Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 374, in main
    train_net(args)
  File "train.py", line 242, in train_net
    images_filter        = config.data_images_filter,
  File "/home/puke/insightface/recognition/image_iter.py", line 39, in __init__
    s = self.imgrec.read_idx(0)
  File "/home/puke/envs/face/local/lib/python2.7/site-packages/mxnet/recordio.py", line 318, in read_idx
    return self.read()
  File "/home/puke/envs/face/local/lib/python2.7/site-packages/mxnet/recordio.py", line 209, in read
    ctypes.byref(size)))
  File "/home/puke/envs/face/local/lib/python2.7/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:44:10] src/recordio.cc:65: Check failed: header[0] == RecordIOWriter::kMagic: Invalid RecordIO File

@nttstar 能帮我解答一下吗

**Comment by Vietdung113** [comment]
anyone resolved this problem?

**Comment by ctgushiwei** [comment]
do you have solveed this  problem?

**Comment by ctgushiwei** [comment]
这个应该是作者上传的原始数据压缩包有问题导致解压不了
