### ISSUE TITLE
关于训练的时候使用大量的图片的时候，会出现问题。

### ISSUE THREAD

**Issue by wbj1995** [deepinsight/insightface#924]
testing verification..
Traceback (most recent call last):
  File "train_softmax.py", line 598, in <module>
    main()
  File "train_softmax.py", line 595, in main
    train_net(args)
  File "train_softmax.py", line 589, in train_net
    epoch_end_callback = epoch_cb )
  File "D:\python\lib\site-packages\mxnet\module\base_module.py", line 553, in fit
    callback(batch_end_params)
  File "train_softmax.py", line 527, in _batch_callback
    acc_list = ver_test(mbatch)
  File "train_softmax.py", line 488, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(ver_list[i], model, args.batch_size, 10, None, None)
  File "eval\verification.py", line 247, in test
    _embeddings = net_out[0].asnumpy()
  File "D:\python\lib\site-packages\mxnet\ndarray\ndarray.py", line 1996, in asnumpy
    ctypes.c_size_t(data.size)))
  File "D:\python\lib\site-packages\mxnet\base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:49:45] c:\jenkins\workspace\mxnet-tag\mxnet\include\mxnet\./tensor_blob.h:290: Check failed: this->shape_.Size() == static_cast<size_t>(shape.Size()) (3010560000 vs. 18446744072425144320) : TBlob.get_with_shape: new and old shape do not match total elements
，就是会报这个错误，您能给解释一下么

**Comment by wu1995snow** [comment]
请问你解决这个问题了吗
