### ISSUE TITLE
How RetinaFace fine-tunes based on a trained model

### ISSUE THREAD

**Issue by zhijl** [deepinsight/insightface#932]
As the title shows, I've trained a model on WiderFace, but I want to continue fine-tune the trained model on another new dataset. I pass in parameters in the following way:

``` text
python -u train.py --prefix ./model/retina-p1 --pretrained model/retina-50 --pretrained_epoch 60
```

The models I trained are `retina-50-symbol.json` and `retina-50-60.params`. But the runtime reported the following error:

``` text
...
INFO:root:loading model/retina-50,60
Traceback (most recent call last):
  File "train.py", line 333, in <module>
    main()
  File "train.py", line 330, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train.py", line 93, in train_net
    sym = eval('get_' + args.network + '_train')(sym)
  File "/home/temp/insightface/RetinaFace/rcnn/symbol/symbol_resnet.py", line 409, in get_resnet_train
    return get_sym_train(sym)
  File "/home/temp/insightface/RetinaFace/rcnn/symbol/symbol_common.py", line 448, in get_sym_train
    conv_fpn_feat = get_sym_conv(data, sym)
  File "/home/temp/insightface/RetinaFace/rcnn/symbol/symbol_common.py", line 206, in get_sym_conv
    stride2layer[stride] = all_layers[name]
  File "/home/temp/anaconda3/envs/mxnet/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 511, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "_plus0_output"
```

**Does the current code support fine-tuning?**

**Comment by nttstar** [comment]
Some tiny modifications may required, as now it only supports imagenet-pretrained models.

**Comment by yjhuasheng** [comment]
请问您现在能够在训练好的模型上微调吗

**Comment by yjhuasheng** [comment]
Hi, I also encountered the same problem，Do you solved it？
