### ISSUE TITLE
Failed to allocate CPU Memory: When trying to run train.py under recognition folder

### ISSUE THREAD

**Issue by dprajaram** [deepinsight/insightface#957]
CUDA_VISIBLE_DEVICES='0,1,2,3' python -u train.py --network r100 --loss arcface --dataset emore
gpu num: 4
prefix ./models/r100-arcface-emore/model
image_size [112, 112]
num_classes 85742
Called with argument: Namespace(batch_size=256, ckpt=3, ctx_num=4, dataset='emore', frequent=20, image_channel=3, kvstore='device', loss='arcface', lr=0.1, lr_steps='100000,160000,220000', models_root='./models', mom=0.9, network='r100', per_batch_size=64, pretrained='', pretrained_epoch=1, rescale_threshold=0, verbose=2000, wd=0.0005) {'loss_m1': 1.0, 'loss_m2': 0.5, 'loss_m3': 0.0, 'net_act': 'prelu', 'emb_size': 512, 'data_rand_mirror': True, 'num_layers': 100, 'loss_name': 'margin_softmax', 'val_targets': ['lfw', 'cfp_fp', 'agedb_30'], 'ce_loss': True, 'net_input': 1, 'image_shape': [112, 112, 3], 'net_blocks': [1, 4, 6, 2], 'fc7_lr_mult': 1.0, 'ckpt_embedding': True, 'net_unit': 3, 'net_output': 'E', 'count_flops': True, 'num_workers': 1, 'batch_size': 256, 'memonger': False, 'data_images_filter': 0, 'dataset': 'emore', 'num_classes': 85742, 'fc7_no_bias': False, 'loss': 'arcface', 'data_color': 0, 'loss_s': 64.0, 'dataset_path': '../datasets/faces_emore', 'data_cutoff': False, 'net_se': 0, 'net_multiplier': 1.0, 'fc7_wd_mult': 1.0, 'network': 'r100', 'per_batch_size': 64, 'net_name': 'fresnet', 'workspace': 256, 'max_steps': 0, 'bn_mom': 0.9}
0 1 E 3 prelu False
Network FLOPs: 24.2G
INFO:root:loading recordio ../datasets/faces_emore/train.rec...
header0 label [5822654. 5908396.]
id2range 85742
5822653
rand_mirror True
../datasets/faces_emore/lfw.bin
Image isze
[112, 112]
loading bin 0
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
(12000, 3, 112, 112)
ver lfw
../datasets/faces_emore/cfp_fp.bin
Image isze
[112, 112]
Traceback (most recent call last):
  File "train.py", line 389, in <module>
    main()
  File "train.py", line 385, in main
    train_net(args)
  File "train.py", line 276, in train_net
    data_set = verification.load_bin(path, image_size)
  File "eval/verification.py", line 197, in load_bin
    data = nd.empty((len(issame_list) * 2, 3, image_size[0], image_size[1]))
  File "/home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 103, in empty
    return _empty_ndarray(shape, ctx, dtype)
  File "/home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/ndarray/ndarray.py", line 3955, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/ndarray/ndarray.py", line 141, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:17:21] src/storage/./cpu_device_storage.h:75: Failed to allocate CPU Memory
Stack trace:
  [bt] (0) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4b03ab) [0x7f4ad02313ab]
  [bt] (1) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2e618c1) [0x7f4ad2be28c1]
  [bt] (2) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2e6a96f) [0x7f4ad2beb96f]
  [bt] (3) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::NDArray::NDArray(mxnet::TShape const&, mxnet::Context, bool, int)+0x5d0) [0x7f4ad22b25b0]
  [bt] (4) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/site-packages/mxnet/libmxnet.so(MXNDArrayCreateEx+0x22d) [0x7f4ad22b307d]
  [bt] (5) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7f4b04f1857c]
  [bt] (6) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7f4b04f17cd5]
  [bt] (7) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7f4b04f0f376]
  [bt] (8) /home/testuser/anaconda2/envs/pytorch/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7f4b04f06db3]

**Comment by orlevit** [comment]
I had the same issue, solved it by reducing the batch size in the config.py
