### ISSUE TITLE
Test.py eror

### ISSUE THREAD

**Issue by swed397** [deepinsight/insightface#984]
I tried start deploy/test.py and have this errors:
[16:21:12] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[16:21:12] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "/home/kudryavcev-ra/PycharmProjects/insightface-masterTEST/deploy/test.py", line 18, in <module>
    model = face_model.FaceModel(args)
  File "/home/kudryavcev-ra/PycharmProjects/insightface-masterTEST/deploy/face_model.py", line 53, in __init__
    self.model = get_model(ctx, image_size, args.model, 'fc1')
  File "/home/kudryavcev-ra/PycharmProjects/insightface-masterTEST/deploy/face_model.py", line 39, in get_model
    model.bind(data_shapes=[('data', (1, 3, image_size[0], image_size[1]))])
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 112, 112)
[16:21:14] src/storage/storage.cc:116: Compile with USE_CUDA=1 to enable GPU usage
what i need to do if i want test on cpu and how i can fix this errors

**Comment by marcobarnobi** [comment]
I think that they address it here:
https://github.com/deepinsight/insightface/issues/870

**Comment by bartolootrit** [comment]
You may try to change this line `ctx = mx.gpu(args.gpu)` to `ctx = mx.cpu()` in https://github.com/deepinsight/insightface/blob/master/deploy/face_model.py#L46
