### ISSUE TITLE
RetinaFace default weight decay

### ISSUE THREAD

**Issue by Jeffwhen** [deepinsight/insightface#992]
https://github.com/deepinsight/insightface/blob/4a4b8d03fec981912fdef5b3232a37a827cbeed6/RetinaFace/train.py#L344

I am trying to train RetinaFace using resnet as backbone network. I ran into this error

```
Traceback (most recent call last):
  File "train.py", line 367, in <module>
    main()
  File "train.py", line 350, in main
    args = parse_args()
  File "train.py", line 344, in parse_args
    parser.add_argument('--wd', help='weight decay', default=default.wd, type=float)
AttributeError: 'EasyDict' object has no attribute 'wd'
```
Seems like there should be a `default.wd` specified in `config.py`. What's the proper weight decay?

**Comment by ThanhPham1987** [comment]
Hi Jeffwhen,
You have to replace this line parser.add_argument('--wd', help='weight decay', default=default.wd, type=float)
by parser.add_argument('--wd', help='weight decay', default=0.0005, type=float)
Any concern to issue, please contact via skype: quangthanh1987
Best regards,
PeterPham

**Comment by HoaiBaoHuynh** [comment]
CUDA_VISIBLE_DEVICES= '0,1,2,3'
!python -u train.py --prefix ./model/retina --network resnet

I am trying to train RetinaFace using resnet with Google Colaboratory.I ran into this error

Traceback (most recent call last):
  File "train.py", line 372, in <module>
    main()
  File "train.py", line 359, in main
    cvd = os.environ['CUDA_VISIBLE_DEVICES'].strip()
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

It seems the mxnet version does not match the CUDA version.
